'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
'
Namespace WS_MB_CHECK_LENUM_WITH_LGPLA
    
    'CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZWS_MB_CHECK_LENUM_WITH_LGPLA", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZWS_MB_CHECK_LENUM_WITH_LGPLA
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZwmMbCheckLenumWithLgplaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WM_Win_PanariaUSA.My.MySettings.Default.WM_Win_PanariaUSA_WS_MB_CHECK_LENUM_WITH_LGPLA_ZWS_MB_CHECK_LENUM_WITH_LGPLA
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZwmMbCheckLenumWithLgplaCompleted As ZwmMbCheckLenumWithLgplaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWS_MB_CHECK_LENUM_WITH_LGPLA:Zw"& _ 
            "mMbCheckLenumWithLgplaRequest", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZwmMbCheckLenumWithLgpla(<System.Xml.Serialization.XmlElementAttribute("ZwmMbCheckLenumWithLgpla", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ByVal ZwmMbCheckLenumWithLgpla1 As ZwmMbCheckLenumWithLgpla) As <System.Xml.Serialization.XmlElementAttribute("ZwmMbCheckLenumWithLgplaResponse", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ZwmMbCheckLenumWithLgplaResponse
            Dim results() As Object = Me.Invoke("ZwmMbCheckLenumWithLgpla", New Object() {ZwmMbCheckLenumWithLgpla1})
            Return CType(results(0),ZwmMbCheckLenumWithLgplaResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZwmMbCheckLenumWithLgplaAsync(ByVal ZwmMbCheckLenumWithLgpla1 As ZwmMbCheckLenumWithLgpla)
            Me.ZwmMbCheckLenumWithLgplaAsync(ZwmMbCheckLenumWithLgpla1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZwmMbCheckLenumWithLgplaAsync(ByVal ZwmMbCheckLenumWithLgpla1 As ZwmMbCheckLenumWithLgpla, ByVal userState As Object)
            If (Me.ZwmMbCheckLenumWithLgplaOperationCompleted Is Nothing) Then
                Me.ZwmMbCheckLenumWithLgplaOperationCompleted = AddressOf Me.OnZwmMbCheckLenumWithLgplaOperationCompleted
            End If
            Me.InvokeAsync("ZwmMbCheckLenumWithLgpla", New Object() {ZwmMbCheckLenumWithLgpla1}, Me.ZwmMbCheckLenumWithLgplaOperationCompleted, userState)
        End Sub
        
        Private Sub OnZwmMbCheckLenumWithLgplaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ZwmMbCheckLenumWithLgplaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZwmMbCheckLenumWithLgplaCompleted(Me, New ZwmMbCheckLenumWithLgplaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmMbCheckLenumWithLgpla
        
        Private iCheckOnProductionField As String
        
        Private iEnableDebugField As String
        
        Private iLanguageField As String
        
        Private iLenumField As String
        
        Private iLgnumField As String
        
        Private iLgplaField As String
        
        Private iLgtypField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ICheckOnProduction() As String
            Get
                Return Me.iCheckOnProductionField
            End Get
            Set
                Me.iCheckOnProductionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IEnableDebug() As String
            Get
                Return Me.iEnableDebugField
            End Get
            Set
                Me.iEnableDebugField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ILanguage() As String
            Get
                Return Me.iLanguageField
            End Get
            Set
                Me.iLanguageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ILenum() As String
            Get
                Return Me.iLenumField
            End Get
            Set
                Me.iLenumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ILgnum() As String
            Get
                Return Me.iLgnumField
            End Get
            Set
                Me.iLgnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ILgpla() As String
            Get
                Return Me.iLgplaField
            End Get
            Set
                Me.iLgplaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ILgtyp() As String
            Get
                Return Me.iLgtypField
            End Get
            Set
                Me.iLgtypField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class Lqua
        
        Private mandtField As String
        
        Private lgnumField As String
        
        Private lqnumField As String
        
        Private matnrField As String
        
        Private werksField As String
        
        Private chargField As String
        
        Private bestqField As String
        
        Private sobkzField As String
        
        Private sonumField As String
        
        Private lgtypField As String
        
        Private lgplaField As String
        
        Private plposField As String
        
        Private skzueField As String
        
        Private skzuaField As String
        
        Private skzseField As String
        
        Private skzsaField As String
        
        Private skzsiField As String
        
        Private spgruField As String
        
        Private zeugnField As String
        
        Private bdatuField As String
        
        Private bzeitField As String
        
        Private btanrField As String
        
        Private btapsField As String
        
        Private edatuField As String
        
        Private ezeitField As String
        
        Private adatuField As String
        
        Private azeitField As String
        
        Private zdatuField As String
        
        Private wdatuField As String
        
        Private wenumField As String
        
        Private weposField As String
        
        Private letypField As String
        
        Private meinsField As String
        
        Private gesmeField As Decimal
        
        Private vermeField As Decimal
        
        Private einmeField As Decimal
        
        Private ausmeField As Decimal
        
        Private mgewiField As Decimal
        
        Private geweiField As String
        
        Private tbnumField As String
        
        Private ivnumField As String
        
        Private ivposField As String
        
        Private betypField As String
        
        Private benumField As String
        
        Private lenumField As String
        
        Private qplosField As String
        
        Private vfdatField As String
        
        Private qkapvField As Decimal
        
        Private koberField As String
        
        Private lgortField As String
        
        Private virgoField As String
        
        Private trameField As Decimal
        
        Private kzhuqField As String
        
        Private vbelnField As String
        
        Private posnrField As String
        
        Private idatuField As String
        
        Private msrInspGuidField() As Byte
        
        Private sgtScatField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgnum() As String
            Get
                Return Me.lgnumField
            End Get
            Set
                Me.lgnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lqnum() As String
            Get
                Return Me.lqnumField
            End Get
            Set
                Me.lqnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Matnr() As String
            Get
                Return Me.matnrField
            End Get
            Set
                Me.matnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Werks() As String
            Get
                Return Me.werksField
            End Get
            Set
                Me.werksField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Charg() As String
            Get
                Return Me.chargField
            End Get
            Set
                Me.chargField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Bestq() As String
            Get
                Return Me.bestqField
            End Get
            Set
                Me.bestqField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sobkz() As String
            Get
                Return Me.sobkzField
            End Get
            Set
                Me.sobkzField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sonum() As String
            Get
                Return Me.sonumField
            End Get
            Set
                Me.sonumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgtyp() As String
            Get
                Return Me.lgtypField
            End Get
            Set
                Me.lgtypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgpla() As String
            Get
                Return Me.lgplaField
            End Get
            Set
                Me.lgplaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Plpos() As String
            Get
                Return Me.plposField
            End Get
            Set
                Me.plposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Skzue() As String
            Get
                Return Me.skzueField
            End Get
            Set
                Me.skzueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Skzua() As String
            Get
                Return Me.skzuaField
            End Get
            Set
                Me.skzuaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Skzse() As String
            Get
                Return Me.skzseField
            End Get
            Set
                Me.skzseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Skzsa() As String
            Get
                Return Me.skzsaField
            End Get
            Set
                Me.skzsaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Skzsi() As String
            Get
                Return Me.skzsiField
            End Get
            Set
                Me.skzsiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Spgru() As String
            Get
                Return Me.spgruField
            End Get
            Set
                Me.spgruField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zeugn() As String
            Get
                Return Me.zeugnField
            End Get
            Set
                Me.zeugnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Bdatu() As String
            Get
                Return Me.bdatuField
            End Get
            Set
                Me.bdatuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Bzeit() As String
            Get
                Return Me.bzeitField
            End Get
            Set
                Me.bzeitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Btanr() As String
            Get
                Return Me.btanrField
            End Get
            Set
                Me.btanrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Btaps() As String
            Get
                Return Me.btapsField
            End Get
            Set
                Me.btapsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Edatu() As String
            Get
                Return Me.edatuField
            End Get
            Set
                Me.edatuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ezeit() As String
            Get
                Return Me.ezeitField
            End Get
            Set
                Me.ezeitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Adatu() As String
            Get
                Return Me.adatuField
            End Get
            Set
                Me.adatuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Azeit() As String
            Get
                Return Me.azeitField
            End Get
            Set
                Me.azeitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zdatu() As String
            Get
                Return Me.zdatuField
            End Get
            Set
                Me.zdatuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Wdatu() As String
            Get
                Return Me.wdatuField
            End Get
            Set
                Me.wdatuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Wenum() As String
            Get
                Return Me.wenumField
            End Get
            Set
                Me.wenumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Wepos() As String
            Get
                Return Me.weposField
            End Get
            Set
                Me.weposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Letyp() As String
            Get
                Return Me.letypField
            End Get
            Set
                Me.letypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Meins() As String
            Get
                Return Me.meinsField
            End Get
            Set
                Me.meinsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Gesme() As Decimal
            Get
                Return Me.gesmeField
            End Get
            Set
                Me.gesmeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Verme() As Decimal
            Get
                Return Me.vermeField
            End Get
            Set
                Me.vermeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Einme() As Decimal
            Get
                Return Me.einmeField
            End Get
            Set
                Me.einmeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ausme() As Decimal
            Get
                Return Me.ausmeField
            End Get
            Set
                Me.ausmeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mgewi() As Decimal
            Get
                Return Me.mgewiField
            End Get
            Set
                Me.mgewiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Gewei() As String
            Get
                Return Me.geweiField
            End Get
            Set
                Me.geweiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tbnum() As String
            Get
                Return Me.tbnumField
            End Get
            Set
                Me.tbnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ivnum() As String
            Get
                Return Me.ivnumField
            End Get
            Set
                Me.ivnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ivpos() As String
            Get
                Return Me.ivposField
            End Get
            Set
                Me.ivposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Betyp() As String
            Get
                Return Me.betypField
            End Get
            Set
                Me.betypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Benum() As String
            Get
                Return Me.benumField
            End Get
            Set
                Me.benumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lenum() As String
            Get
                Return Me.lenumField
            End Get
            Set
                Me.lenumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Qplos() As String
            Get
                Return Me.qplosField
            End Get
            Set
                Me.qplosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vfdat() As String
            Get
                Return Me.vfdatField
            End Get
            Set
                Me.vfdatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Qkapv() As Decimal
            Get
                Return Me.qkapvField
            End Get
            Set
                Me.qkapvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kober() As String
            Get
                Return Me.koberField
            End Get
            Set
                Me.koberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgort() As String
            Get
                Return Me.lgortField
            End Get
            Set
                Me.lgortField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Virgo() As String
            Get
                Return Me.virgoField
            End Get
            Set
                Me.virgoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Trame() As Decimal
            Get
                Return Me.trameField
            End Get
            Set
                Me.trameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzhuq() As String
            Get
                Return Me.kzhuqField
            End Get
            Set
                Me.kzhuqField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vbeln() As String
            Get
                Return Me.vbelnField
            End Get
            Set
                Me.vbelnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Posnr() As String
            Get
                Return Me.posnrField
            End Get
            Set
                Me.posnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idatu() As String
            Get
                Return Me.idatuField
            End Get
            Set
                Me.idatuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property MsrInspGuid() As Byte()
            Get
                Return Me.msrInspGuidField
            End Get
            Set
                Me.msrInspGuidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SgtScat() As String
            Get
                Return Me.sgtScatField
            End Get
            Set
                Me.sgtScatField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class Lagp
        
        Private mandtField As String
        
        Private lgnumField As String
        
        Private lgtypField As String
        
        Private lgplaField As String
        
        Private lgberField As String
        
        Private lptypField As String
        
        Private plaufField As String
        
        Private skzuaField As String
        
        Private skzueField As String
        
        Private skzsaField As String
        
        Private skzseField As String
        
        Private skzsiField As String
        
        Private spgruField As String
        
        Private anzquField As Decimal
        
        Private maxquField As Decimal
        
        Private anzleField As Decimal
        
        Private maxleField As Decimal
        
        Private kzdynField As String
        
        Private lgewiField As Decimal
        
        Private geweiField As String
        
        Private mgewiField As Decimal
        
        Private bdatuField As String
        
        Private bzeitField As String
        
        Private btanrField As String
        
        Private btapsField As String
        
        Private rdatuField As String
        
        Private rzeitField As String
        
        Private kzinvField As String
        
        Private idatuField As String
        
        Private ivnumField As String
        
        Private ivposField As String
        
        Private ivivoField As String
        
        Private kzlerField As String
        
        Private kzvolField As String
        
        Private sorlpField As String
        
        Private brandField As String
        
        Private unameField As String
        
        Private laedtField As String
        
        Private lkapvField As Decimal
        
        Private rkapvField As Decimal
        
        Private koberField As String
        
        Private reihfField As String
        
        Private verifField As String
        
        Private lzoneField As String
        
        Private xcordField As Decimal
        
        Private ycordField As Decimal
        
        Private zcordField As Decimal
        
        Private zexclFirstPickField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgnum() As String
            Get
                Return Me.lgnumField
            End Get
            Set
                Me.lgnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgtyp() As String
            Get
                Return Me.lgtypField
            End Get
            Set
                Me.lgtypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgpla() As String
            Get
                Return Me.lgplaField
            End Get
            Set
                Me.lgplaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgber() As String
            Get
                Return Me.lgberField
            End Get
            Set
                Me.lgberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lptyp() As String
            Get
                Return Me.lptypField
            End Get
            Set
                Me.lptypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Plauf() As String
            Get
                Return Me.plaufField
            End Get
            Set
                Me.plaufField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Skzua() As String
            Get
                Return Me.skzuaField
            End Get
            Set
                Me.skzuaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Skzue() As String
            Get
                Return Me.skzueField
            End Get
            Set
                Me.skzueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Skzsa() As String
            Get
                Return Me.skzsaField
            End Get
            Set
                Me.skzsaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Skzse() As String
            Get
                Return Me.skzseField
            End Get
            Set
                Me.skzseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Skzsi() As String
            Get
                Return Me.skzsiField
            End Get
            Set
                Me.skzsiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Spgru() As String
            Get
                Return Me.spgruField
            End Get
            Set
                Me.spgruField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Anzqu() As Decimal
            Get
                Return Me.anzquField
            End Get
            Set
                Me.anzquField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Maxqu() As Decimal
            Get
                Return Me.maxquField
            End Get
            Set
                Me.maxquField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Anzle() As Decimal
            Get
                Return Me.anzleField
            End Get
            Set
                Me.anzleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Maxle() As Decimal
            Get
                Return Me.maxleField
            End Get
            Set
                Me.maxleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzdyn() As String
            Get
                Return Me.kzdynField
            End Get
            Set
                Me.kzdynField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgewi() As Decimal
            Get
                Return Me.lgewiField
            End Get
            Set
                Me.lgewiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Gewei() As String
            Get
                Return Me.geweiField
            End Get
            Set
                Me.geweiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mgewi() As Decimal
            Get
                Return Me.mgewiField
            End Get
            Set
                Me.mgewiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Bdatu() As String
            Get
                Return Me.bdatuField
            End Get
            Set
                Me.bdatuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Bzeit() As String
            Get
                Return Me.bzeitField
            End Get
            Set
                Me.bzeitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Btanr() As String
            Get
                Return Me.btanrField
            End Get
            Set
                Me.btanrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Btaps() As String
            Get
                Return Me.btapsField
            End Get
            Set
                Me.btapsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rdatu() As String
            Get
                Return Me.rdatuField
            End Get
            Set
                Me.rdatuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rzeit() As String
            Get
                Return Me.rzeitField
            End Get
            Set
                Me.rzeitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzinv() As String
            Get
                Return Me.kzinvField
            End Get
            Set
                Me.kzinvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idatu() As String
            Get
                Return Me.idatuField
            End Get
            Set
                Me.idatuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ivnum() As String
            Get
                Return Me.ivnumField
            End Get
            Set
                Me.ivnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ivpos() As String
            Get
                Return Me.ivposField
            End Get
            Set
                Me.ivposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ivivo() As String
            Get
                Return Me.ivivoField
            End Get
            Set
                Me.ivivoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzler() As String
            Get
                Return Me.kzlerField
            End Get
            Set
                Me.kzlerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzvol() As String
            Get
                Return Me.kzvolField
            End Get
            Set
                Me.kzvolField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sorlp() As String
            Get
                Return Me.sorlpField
            End Get
            Set
                Me.sorlpField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Brand() As String
            Get
                Return Me.brandField
            End Get
            Set
                Me.brandField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Uname() As String
            Get
                Return Me.unameField
            End Get
            Set
                Me.unameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Laedt() As String
            Get
                Return Me.laedtField
            End Get
            Set
                Me.laedtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lkapv() As Decimal
            Get
                Return Me.lkapvField
            End Get
            Set
                Me.lkapvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rkapv() As Decimal
            Get
                Return Me.rkapvField
            End Get
            Set
                Me.rkapvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kober() As String
            Get
                Return Me.koberField
            End Get
            Set
                Me.koberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Reihf() As String
            Get
                Return Me.reihfField
            End Get
            Set
                Me.reihfField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Verif() As String
            Get
                Return Me.verifField
            End Get
            Set
                Me.verifField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lzone() As String
            Get
                Return Me.lzoneField
            End Get
            Set
                Me.lzoneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Xcord() As Decimal
            Get
                Return Me.xcordField
            End Get
            Set
                Me.xcordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ycord() As Decimal
            Get
                Return Me.ycordField
            End Get
            Set
                Me.ycordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zcord() As Decimal
            Get
                Return Me.zcordField
            End Get
            Set
                Me.zcordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZexclFirstPick() As String
            Get
                Return Me.zexclFirstPickField
            End Get
            Set
                Me.zexclFirstPickField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmMbCheckLenumWithLgplaResponse
        
        Private eCheckLenumOkField As String
        
        Private eCheckLenumWithLgplaOkField As String
        
        Private eCheckLgplaOkField As String
        
        Private eErrorCodeField As String
        
        Private eErrorDescriptionField As String
        
        Private eErrorSubrcField As Integer
        
        Private eFoundrowsField As Integer
        
        Private eGestioneUmAttivaField As String
        
        Private eLagpField As Lagp
        
        Private eLquaTabField() As Lqua
        
        Private eSuccessField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ECheckLenumOk() As String
            Get
                Return Me.eCheckLenumOkField
            End Get
            Set
                Me.eCheckLenumOkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ECheckLenumWithLgplaOk() As String
            Get
                Return Me.eCheckLenumWithLgplaOkField
            End Get
            Set
                Me.eCheckLenumWithLgplaOkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ECheckLgplaOk() As String
            Get
                Return Me.eCheckLgplaOkField
            End Get
            Set
                Me.eCheckLgplaOkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorCode() As String
            Get
                Return Me.eErrorCodeField
            End Get
            Set
                Me.eErrorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorDescription() As String
            Get
                Return Me.eErrorDescriptionField
            End Get
            Set
                Me.eErrorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorSubrc() As Integer
            Get
                Return Me.eErrorSubrcField
            End Get
            Set
                Me.eErrorSubrcField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EFoundrows() As Integer
            Get
                Return Me.eFoundrowsField
            End Get
            Set
                Me.eFoundrowsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EGestioneUmAttiva() As String
            Get
                Return Me.eGestioneUmAttivaField
            End Get
            Set
                Me.eGestioneUmAttivaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ELagp() As Lagp
            Get
                Return Me.eLagpField
            End Get
            Set
                Me.eLagpField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property ELquaTab() As Lqua()
            Get
                Return Me.eLquaTabField
            End Get
            Set
                Me.eLquaTabField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ESuccess() As String
            Get
                Return Me.eSuccessField
            End Get
            Set
                Me.eSuccessField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ZwmMbCheckLenumWithLgplaCompletedEventHandler(ByVal sender As Object, ByVal e As ZwmMbCheckLenumWithLgplaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZwmMbCheckLenumWithLgplaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZwmMbCheckLenumWithLgplaResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZwmMbCheckLenumWithLgplaResponse)
            End Get
        End Property
    End Class
End Namespace
