'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
'
Namespace WS_MB_GET_UBICAZIONI_INFO
    
    'CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZWS_MB_GET_UBICAZIONI_INFO", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZWS_MB_GET_UBICAZIONI_INFO
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZwmMbGetUbicazioniInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WM_Win_PanariaUSA.My.MySettings.Default.WM_Win_PanariaUSA_WS_MB_GET_UBICAZIONI_INFO_ZWS_MB_GET_UBICAZIONI_INFO
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZwmMbGetUbicazioniInfoCompleted As ZwmMbGetUbicazioniInfoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWS_MB_GET_UBICAZIONI_INFO:ZwmMb"& _ 
            "GetUbicazioniInfoRequest", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZwmMbGetUbicazioniInfo(<System.Xml.Serialization.XmlElementAttribute("ZwmMbGetUbicazioniInfo", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ByVal ZwmMbGetUbicazioniInfo1 As ZwmMbGetUbicazioniInfo) As <System.Xml.Serialization.XmlElementAttribute("ZwmMbGetUbicazioniInfoResponse", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ZwmMbGetUbicazioniInfoResponse
            Dim results() As Object = Me.Invoke("ZwmMbGetUbicazioniInfo", New Object() {ZwmMbGetUbicazioniInfo1})
            Return CType(results(0),ZwmMbGetUbicazioniInfoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZwmMbGetUbicazioniInfoAsync(ByVal ZwmMbGetUbicazioniInfo1 As ZwmMbGetUbicazioniInfo)
            Me.ZwmMbGetUbicazioniInfoAsync(ZwmMbGetUbicazioniInfo1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZwmMbGetUbicazioniInfoAsync(ByVal ZwmMbGetUbicazioniInfo1 As ZwmMbGetUbicazioniInfo, ByVal userState As Object)
            If (Me.ZwmMbGetUbicazioniInfoOperationCompleted Is Nothing) Then
                Me.ZwmMbGetUbicazioniInfoOperationCompleted = AddressOf Me.OnZwmMbGetUbicazioniInfoOperationCompleted
            End If
            Me.InvokeAsync("ZwmMbGetUbicazioniInfo", New Object() {ZwmMbGetUbicazioniInfo1}, Me.ZwmMbGetUbicazioniInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnZwmMbGetUbicazioniInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ZwmMbGetUbicazioniInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZwmMbGetUbicazioniInfoCompleted(Me, New ZwmMbGetUbicazioniInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmMbGetUbicazioniInfo
        
        Private iEnableDebugField As String
        
        Private iLanguageField As String
        
        Private iLgnumField As String
        
        Private iLgplaField As String
        
        Private iLgtypField As String
        
        Private iStatoUbicazioneField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IEnableDebug() As String
            Get
                Return Me.iEnableDebugField
            End Get
            Set
                Me.iEnableDebugField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ILanguage() As String
            Get
                Return Me.iLanguageField
            End Get
            Set
                Me.iLanguageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ILgnum() As String
            Get
                Return Me.iLgnumField
            End Get
            Set
                Me.iLgnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ILgpla() As String
            Get
                Return Me.iLgplaField
            End Get
            Set
                Me.iLgplaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ILgtyp() As String
            Get
                Return Me.iLgtypField
            End Get
            Set
                Me.iLgtypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IStatoUbicazione() As String
            Get
                Return Me.iStatoUbicazioneField
            End Get
            Set
                Me.iStatoUbicazioneField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class Ze1WsLagp
        
        Private mandtField As String
        
        Private lgnumField As String
        
        Private lgtypField As String
        
        Private lgplaField As String
        
        Private lgberField As String
        
        Private lptypField As String
        
        Private plaufField As String
        
        Private skzuaField As String
        
        Private skzueField As String
        
        Private skzsaField As String
        
        Private skzseField As String
        
        Private skzsiField As String
        
        Private spgruField As String
        
        Private anzquField As Decimal
        
        Private maxquField As Decimal
        
        Private anzleField As Decimal
        
        Private maxleField As Decimal
        
        Private kzdynField As String
        
        Private lgewiField As Decimal
        
        Private geweiField As String
        
        Private mgewiField As Decimal
        
        Private bdatuField As String
        
        Private bzeitField As String
        
        Private btanrField As String
        
        Private btapsField As String
        
        Private rdatuField As String
        
        Private rzeitField As String
        
        Private kzinvField As String
        
        Private idatuField As String
        
        Private ivnumField As String
        
        Private ivposField As String
        
        Private ivivoField As String
        
        Private kzlerField As String
        
        Private kzvolField As String
        
        Private sorlpField As String
        
        Private brandField As String
        
        Private unameField As String
        
        Private laedtField As String
        
        Private lkapvField As Decimal
        
        Private rkapvField As Decimal
        
        Private koberField As String
        
        Private reihfField As String
        
        Private verifField As String
        
        Private lzoneField As String
        
        Private xcordField As Decimal
        
        Private ycordField As Decimal
        
        Private zcordField As Decimal
        
        Private zexclFirstPickField As String
        
        Private ubiPienaField As String
        
        Private statoUbicazioneField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgnum() As String
            Get
                Return Me.lgnumField
            End Get
            Set
                Me.lgnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgtyp() As String
            Get
                Return Me.lgtypField
            End Get
            Set
                Me.lgtypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgpla() As String
            Get
                Return Me.lgplaField
            End Get
            Set
                Me.lgplaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgber() As String
            Get
                Return Me.lgberField
            End Get
            Set
                Me.lgberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lptyp() As String
            Get
                Return Me.lptypField
            End Get
            Set
                Me.lptypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Plauf() As String
            Get
                Return Me.plaufField
            End Get
            Set
                Me.plaufField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Skzua() As String
            Get
                Return Me.skzuaField
            End Get
            Set
                Me.skzuaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Skzue() As String
            Get
                Return Me.skzueField
            End Get
            Set
                Me.skzueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Skzsa() As String
            Get
                Return Me.skzsaField
            End Get
            Set
                Me.skzsaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Skzse() As String
            Get
                Return Me.skzseField
            End Get
            Set
                Me.skzseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Skzsi() As String
            Get
                Return Me.skzsiField
            End Get
            Set
                Me.skzsiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Spgru() As String
            Get
                Return Me.spgruField
            End Get
            Set
                Me.spgruField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Anzqu() As Decimal
            Get
                Return Me.anzquField
            End Get
            Set
                Me.anzquField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Maxqu() As Decimal
            Get
                Return Me.maxquField
            End Get
            Set
                Me.maxquField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Anzle() As Decimal
            Get
                Return Me.anzleField
            End Get
            Set
                Me.anzleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Maxle() As Decimal
            Get
                Return Me.maxleField
            End Get
            Set
                Me.maxleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzdyn() As String
            Get
                Return Me.kzdynField
            End Get
            Set
                Me.kzdynField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgewi() As Decimal
            Get
                Return Me.lgewiField
            End Get
            Set
                Me.lgewiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Gewei() As String
            Get
                Return Me.geweiField
            End Get
            Set
                Me.geweiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mgewi() As Decimal
            Get
                Return Me.mgewiField
            End Get
            Set
                Me.mgewiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Bdatu() As String
            Get
                Return Me.bdatuField
            End Get
            Set
                Me.bdatuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Bzeit() As String
            Get
                Return Me.bzeitField
            End Get
            Set
                Me.bzeitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Btanr() As String
            Get
                Return Me.btanrField
            End Get
            Set
                Me.btanrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Btaps() As String
            Get
                Return Me.btapsField
            End Get
            Set
                Me.btapsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rdatu() As String
            Get
                Return Me.rdatuField
            End Get
            Set
                Me.rdatuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rzeit() As String
            Get
                Return Me.rzeitField
            End Get
            Set
                Me.rzeitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzinv() As String
            Get
                Return Me.kzinvField
            End Get
            Set
                Me.kzinvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idatu() As String
            Get
                Return Me.idatuField
            End Get
            Set
                Me.idatuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ivnum() As String
            Get
                Return Me.ivnumField
            End Get
            Set
                Me.ivnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ivpos() As String
            Get
                Return Me.ivposField
            End Get
            Set
                Me.ivposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ivivo() As String
            Get
                Return Me.ivivoField
            End Get
            Set
                Me.ivivoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzler() As String
            Get
                Return Me.kzlerField
            End Get
            Set
                Me.kzlerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzvol() As String
            Get
                Return Me.kzvolField
            End Get
            Set
                Me.kzvolField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sorlp() As String
            Get
                Return Me.sorlpField
            End Get
            Set
                Me.sorlpField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Brand() As String
            Get
                Return Me.brandField
            End Get
            Set
                Me.brandField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Uname() As String
            Get
                Return Me.unameField
            End Get
            Set
                Me.unameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Laedt() As String
            Get
                Return Me.laedtField
            End Get
            Set
                Me.laedtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lkapv() As Decimal
            Get
                Return Me.lkapvField
            End Get
            Set
                Me.lkapvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rkapv() As Decimal
            Get
                Return Me.rkapvField
            End Get
            Set
                Me.rkapvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kober() As String
            Get
                Return Me.koberField
            End Get
            Set
                Me.koberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Reihf() As String
            Get
                Return Me.reihfField
            End Get
            Set
                Me.reihfField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Verif() As String
            Get
                Return Me.verifField
            End Get
            Set
                Me.verifField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lzone() As String
            Get
                Return Me.lzoneField
            End Get
            Set
                Me.lzoneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Xcord() As Decimal
            Get
                Return Me.xcordField
            End Get
            Set
                Me.xcordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ycord() As Decimal
            Get
                Return Me.ycordField
            End Get
            Set
                Me.ycordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zcord() As Decimal
            Get
                Return Me.zcordField
            End Get
            Set
                Me.zcordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZexclFirstPick() As String
            Get
                Return Me.zexclFirstPickField
            End Get
            Set
                Me.zexclFirstPickField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UbiPiena() As String
            Get
                Return Me.ubiPienaField
            End Get
            Set
                Me.ubiPienaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property StatoUbicazione() As String
            Get
                Return Me.statoUbicazioneField
            End Get
            Set
                Me.statoUbicazioneField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class Bapiret2
        
        Private typeField As String
        
        Private idField As String
        
        Private numberField As String
        
        Private messageField As String
        
        Private logNoField As String
        
        Private logMsgNoField As String
        
        Private messageV1Field As String
        
        Private messageV2Field As String
        
        Private messageV3Field As String
        
        Private messageV4Field As String
        
        Private parameterField As String
        
        Private rowField As Integer
        
        Private fieldField As String
        
        Private systemField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set(value As String)
                Me.typeField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Number() As String
            Get
                Return Me.numberField
            End Get
            Set(value As String)
                Me.numberField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set(value As String)
                Me.messageField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property LogNo() As String
            Get
                Return Me.logNoField
            End Get
            Set(value As String)
                Me.logNoField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property LogMsgNo() As String
            Get
                Return Me.logMsgNoField
            End Get
            Set(value As String)
                Me.logMsgNoField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV1() As String
            Get
                Return Me.messageV1Field
            End Get
            Set(value As String)
                Me.messageV1Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV2() As String
            Get
                Return Me.messageV2Field
            End Get
            Set(value As String)
                Me.messageV2Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV3() As String
            Get
                Return Me.messageV3Field
            End Get
            Set(value As String)
                Me.messageV3Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV4() As String
            Get
                Return Me.messageV4Field
            End Get
            Set(value As String)
                Me.messageV4Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Parameter() As String
            Get
                Return Me.parameterField
            End Get
            Set(value As String)
                Me.parameterField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Row() As Integer
            Get
                Return Me.rowField
            End Get
            Set(value As Integer)
                Me.rowField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Field() As String
            Get
                Return Me.fieldField
            End Get
            Set(value As String)
                Me.fieldField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property System() As String
            Get
                Return Me.systemField
            End Get
            Set(value As String)
                Me.systemField = Value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmMbGetUbicazioniInfoResponse
        
        Private eErrorCodeField As String
        
        Private eErrorDescriptionField As String
        
        Private eErrorSubrcField As Integer
        
        Private eFoundrowsField As Integer
        
        Private eReturnField As Bapiret2
        
        Private eSuccessField As String
        
        Private eTabLagpField() As Ze1WsLagp
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorCode() As String
            Get
                Return Me.eErrorCodeField
            End Get
            Set
                Me.eErrorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorDescription() As String
            Get
                Return Me.eErrorDescriptionField
            End Get
            Set
                Me.eErrorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorSubrc() As Integer
            Get
                Return Me.eErrorSubrcField
            End Get
            Set
                Me.eErrorSubrcField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EFoundrows() As Integer
            Get
                Return Me.eFoundrowsField
            End Get
            Set
                Me.eFoundrowsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EReturn() As Bapiret2
            Get
                Return Me.eReturnField
            End Get
            Set
                Me.eReturnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ESuccess() As String
            Get
                Return Me.eSuccessField
            End Get
            Set
                Me.eSuccessField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property ETabLagp() As Ze1WsLagp()
            Get
                Return Me.eTabLagpField
            End Get
            Set
                Me.eTabLagpField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ZwmMbGetUbicazioniInfoCompletedEventHandler(ByVal sender As Object, ByVal e As ZwmMbGetUbicazioniInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZwmMbGetUbicazioniInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZwmMbGetUbicazioniInfoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZwmMbGetUbicazioniInfoResponse)
            End Get
        End Property
    End Class
End Namespace
