'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
'
Namespace WS_GET_APP_TRANSLATION
    
    'CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZWS_GET_APP_TRANSLATION", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZWS_GET_APP_TRANSLATION
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZwmsGetAppTranslationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WM_Win_PanariaUSA.My.MySettings.Default.WM_Win_PanariaUSA_WS_GET_APP_TRANSLATION_ZWS_GET_APP_TRANSLATION
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZwmsGetAppTranslationCompleted As ZwmsGetAppTranslationCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWS_GET_APP_TRANSLATION:ZwmsGetA"& _ 
            "ppTranslationRequest", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZwmsGetAppTranslation(<System.Xml.Serialization.XmlElementAttribute("ZwmsGetAppTranslation", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ByVal ZwmsGetAppTranslation1 As ZwmsGetAppTranslation) As <System.Xml.Serialization.XmlElementAttribute("ZwmsGetAppTranslationResponse", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ZwmsGetAppTranslationResponse
            Dim results() As Object = Me.Invoke("ZwmsGetAppTranslation", New Object() {ZwmsGetAppTranslation1})
            Return CType(results(0),ZwmsGetAppTranslationResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZwmsGetAppTranslationAsync(ByVal ZwmsGetAppTranslation1 As ZwmsGetAppTranslation)
            Me.ZwmsGetAppTranslationAsync(ZwmsGetAppTranslation1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZwmsGetAppTranslationAsync(ByVal ZwmsGetAppTranslation1 As ZwmsGetAppTranslation, ByVal userState As Object)
            If (Me.ZwmsGetAppTranslationOperationCompleted Is Nothing) Then
                Me.ZwmsGetAppTranslationOperationCompleted = AddressOf Me.OnZwmsGetAppTranslationOperationCompleted
            End If
            Me.InvokeAsync("ZwmsGetAppTranslation", New Object() {ZwmsGetAppTranslation1}, Me.ZwmsGetAppTranslationOperationCompleted, userState)
        End Sub
        
        Private Sub OnZwmsGetAppTranslationOperationCompleted(ByVal arg As Object)
            If (Not (Me.ZwmsGetAppTranslationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZwmsGetAppTranslationCompleted(Me, New ZwmsGetAppTranslationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmsGetAppTranslation
        
        Private iClasseMessaggioField As String
        
        Private iEnableDebugField As String
        
        Private iLanguageField As String
        
        Private iMsgnrField As String
        
        Private iSprasField As String
        
        Private translationTabField() As ZwmsAppTranslationRec
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IClasseMessaggio() As String
            Get
                Return Me.iClasseMessaggioField
            End Get
            Set
                Me.iClasseMessaggioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IEnableDebug() As String
            Get
                Return Me.iEnableDebugField
            End Get
            Set
                Me.iEnableDebugField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ILanguage() As String
            Get
                Return Me.iLanguageField
            End Get
            Set
                Me.iLanguageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IMsgnr() As String
            Get
                Return Me.iMsgnrField
            End Get
            Set
                Me.iMsgnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ISpras() As String
            Get
                Return Me.iSprasField
            End Get
            Set
                Me.iSprasField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property TranslationTab() As ZwmsAppTranslationRec()
            Get
                Return Me.translationTabField
            End Get
            Set
                Me.translationTabField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmsAppTranslationRec
        
        Private msgnrField As String
        
        Private textField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Msgnr() As String
            Get
                Return Me.msgnrField
            End Get
            Set
                Me.msgnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Text() As String
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmsGetAppTranslationResponse
        
        Private eErrorCodeField As String
        
        Private eErrorDescriptionField As String
        
        Private eErrorSubrcField As Integer
        
        Private eFoundrowsField As Integer
        
        Private eSuccessField As String
        
        Private translationTabField() As ZwmsAppTranslationRec
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorCode() As String
            Get
                Return Me.eErrorCodeField
            End Get
            Set
                Me.eErrorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorDescription() As String
            Get
                Return Me.eErrorDescriptionField
            End Get
            Set
                Me.eErrorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorSubrc() As Integer
            Get
                Return Me.eErrorSubrcField
            End Get
            Set
                Me.eErrorSubrcField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EFoundrows() As Integer
            Get
                Return Me.eFoundrowsField
            End Get
            Set
                Me.eFoundrowsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ESuccess() As String
            Get
                Return Me.eSuccessField
            End Get
            Set
                Me.eSuccessField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property TranslationTab() As ZwmsAppTranslationRec()
            Get
                Return Me.translationTabField
            End Get
            Set
                Me.translationTabField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ZwmsGetAppTranslationCompletedEventHandler(ByVal sender As Object, ByVal e As ZwmsGetAppTranslationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZwmsGetAppTranslationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZwmsGetAppTranslationResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZwmsGetAppTranslationResponse)
            End Get
        End Property
    End Class
End Namespace
