'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
'
Namespace WS_GET_JOB_GROUP_EXEC_INFO
    
    'CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZWS_GET_JOB_GROUP_EXEC_INFO", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZWS_GET_JOB_GROUP_EXEC_INFO
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZwmsGetJobGroupExecInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WM_Win_PanariaUSA.My.MySettings.Default.WM_Win_PanariaUSA_WS_GET_JOB_GROUP_EXEC_INFO_ZWS_GET_JOB_GROUP_EXEC_INFO
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZwmsGetJobGroupExecInfoCompleted As ZwmsGetJobGroupExecInfoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWS_GET_JOB_GROUP_EXEC_INFO:Zwms"& _ 
            "GetJobGroupExecInfoRequest", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZwmsGetJobGroupExecInfo(<System.Xml.Serialization.XmlElementAttribute("ZwmsGetJobGroupExecInfo", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ByVal ZwmsGetJobGroupExecInfo1 As ZwmsGetJobGroupExecInfo) As <System.Xml.Serialization.XmlElementAttribute("ZwmsGetJobGroupExecInfoResponse", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ZwmsGetJobGroupExecInfoResponse
            Dim results() As Object = Me.Invoke("ZwmsGetJobGroupExecInfo", New Object() {ZwmsGetJobGroupExecInfo1})
            Return CType(results(0),ZwmsGetJobGroupExecInfoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZwmsGetJobGroupExecInfoAsync(ByVal ZwmsGetJobGroupExecInfo1 As ZwmsGetJobGroupExecInfo)
            Me.ZwmsGetJobGroupExecInfoAsync(ZwmsGetJobGroupExecInfo1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZwmsGetJobGroupExecInfoAsync(ByVal ZwmsGetJobGroupExecInfo1 As ZwmsGetJobGroupExecInfo, ByVal userState As Object)
            If (Me.ZwmsGetJobGroupExecInfoOperationCompleted Is Nothing) Then
                Me.ZwmsGetJobGroupExecInfoOperationCompleted = AddressOf Me.OnZwmsGetJobGroupExecInfoOperationCompleted
            End If
            Me.InvokeAsync("ZwmsGetJobGroupExecInfo", New Object() {ZwmsGetJobGroupExecInfo1}, Me.ZwmsGetJobGroupExecInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnZwmsGetJobGroupExecInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ZwmsGetJobGroupExecInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZwmsGetJobGroupExecInfoCompleted(Me, New ZwmsGetJobGroupExecInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmsGetJobGroupExecInfo
        
        Private iEnableDebugField As String
        
        Private iSprasField As String
        
        Private iZnrWmsGrpexecField As Integer
        
        Private iZnrWmsGrpexecFieldSpecified As Boolean
        
        Private iZnrWmsJobsField As Integer
        
        Private iZnrWmsJobsgrpField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IEnableDebug() As String
            Get
                Return Me.iEnableDebugField
            End Get
            Set
                Me.iEnableDebugField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ISpras() As String
            Get
                Return Me.iSprasField
            End Get
            Set
                Me.iSprasField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IZnrWmsGrpexec() As Integer
            Get
                Return Me.iZnrWmsGrpexecField
            End Get
            Set
                Me.iZnrWmsGrpexecField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property IZnrWmsGrpexecSpecified() As Boolean
            Get
                Return Me.iZnrWmsGrpexecFieldSpecified
            End Get
            Set
                Me.iZnrWmsGrpexecFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IZnrWmsJobs() As Integer
            Get
                Return Me.iZnrWmsJobsField
            End Get
            Set
                Me.iZnrWmsJobsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IZnrWmsJobsgrp() As String
            Get
                Return Me.iZnrWmsJobsgrpField
            End Get
            Set
                Me.iZnrWmsJobsgrpField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class Bapiret2
        
        Private typeField As String
        
        Private idField As String
        
        Private numberField As String
        
        Private messageField As String
        
        Private logNoField As String
        
        Private logMsgNoField As String
        
        Private messageV1Field As String
        
        Private messageV2Field As String
        
        Private messageV3Field As String
        
        Private messageV4Field As String
        
        Private parameterField As String
        
        Private rowField As Integer
        
        Private fieldField As String
        
        Private systemField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set(value As String)
                Me.typeField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Number() As String
            Get
                Return Me.numberField
            End Get
            Set(value As String)
                Me.numberField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set(value As String)
                Me.messageField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property LogNo() As String
            Get
                Return Me.logNoField
            End Get
            Set(value As String)
                Me.logNoField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property LogMsgNo() As String
            Get
                Return Me.logMsgNoField
            End Get
            Set(value As String)
                Me.logMsgNoField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV1() As String
            Get
                Return Me.messageV1Field
            End Get
            Set(value As String)
                Me.messageV1Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV2() As String
            Get
                Return Me.messageV2Field
            End Get
            Set(value As String)
                Me.messageV2Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV3() As String
            Get
                Return Me.messageV3Field
            End Get
            Set(value As String)
                Me.messageV3Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV4() As String
            Get
                Return Me.messageV4Field
            End Get
            Set(value As String)
                Me.messageV4Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Parameter() As String
            Get
                Return Me.parameterField
            End Get
            Set(value As String)
                Me.parameterField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Row() As Integer
            Get
                Return Me.rowField
            End Get
            Set(value As Integer)
                Me.rowField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Field() As String
            Get
                Return Me.fieldField
            End Get
            Set(value As String)
                Me.fieldField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property System() As String
            Get
                Return Me.systemField
            End Get
            Set(value As String)
                Me.systemField = Value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmsJobGroupexecRec
        
        Private znrWmsJobsField As Integer
        
        Private meinsOriField As String
        
        Private zqtapkOriField As Decimal
        
        Private zqtapkRimanenteField As Decimal
        
        Private zqtaPrelBaseField As Decimal
        
        Private udmQtaprMeinsField As String
        
        Private zqtaPrelConsField As Decimal
        
        Private udmQtaprConsField As String
        
        Private vbelnField As String
        
        Private posnrField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZnrWmsJobs() As Integer
            Get
                Return Me.znrWmsJobsField
            End Get
            Set
                Me.znrWmsJobsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MeinsOri() As String
            Get
                Return Me.meinsOriField
            End Get
            Set
                Me.meinsOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZqtapkOri() As Decimal
            Get
                Return Me.zqtapkOriField
            End Get
            Set
                Me.zqtapkOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZqtapkRimanente() As Decimal
            Get
                Return Me.zqtapkRimanenteField
            End Get
            Set
                Me.zqtapkRimanenteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZqtaPrelBase() As Decimal
            Get
                Return Me.zqtaPrelBaseField
            End Get
            Set
                Me.zqtaPrelBaseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UdmQtaprMeins() As String
            Get
                Return Me.udmQtaprMeinsField
            End Get
            Set
                Me.udmQtaprMeinsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZqtaPrelCons() As Decimal
            Get
                Return Me.zqtaPrelConsField
            End Get
            Set
                Me.zqtaPrelConsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UdmQtaprCons() As String
            Get
                Return Me.udmQtaprConsField
            End Get
            Set
                Me.udmQtaprConsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vbeln() As String
            Get
                Return Me.vbelnField
            End Get
            Set
                Me.vbelnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Posnr() As String
            Get
                Return Me.posnrField
            End Get
            Set
                Me.posnrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmsGetJobGroupExecInfoResponse
        
        Private eErrorCodeField As String
        
        Private eErrorDescriptionField As String
        
        Private eErrorSubrcField As Integer
        
        Private eFoundrowsField As Integer
        
        Private eGroupexecFoundField As String
        
        Private eJobGroupexecTabField() As ZwmsJobGroupexecRec
        
        Private eReturnField As Bapiret2
        
        Private eSuccessField As String
        
        Private eTotalZqtapkOriField As Decimal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorCode() As String
            Get
                Return Me.eErrorCodeField
            End Get
            Set
                Me.eErrorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorDescription() As String
            Get
                Return Me.eErrorDescriptionField
            End Get
            Set
                Me.eErrorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorSubrc() As Integer
            Get
                Return Me.eErrorSubrcField
            End Get
            Set
                Me.eErrorSubrcField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EFoundrows() As Integer
            Get
                Return Me.eFoundrowsField
            End Get
            Set
                Me.eFoundrowsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EGroupexecFound() As String
            Get
                Return Me.eGroupexecFoundField
            End Get
            Set
                Me.eGroupexecFoundField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property EJobGroupexecTab() As ZwmsJobGroupexecRec()
            Get
                Return Me.eJobGroupexecTabField
            End Get
            Set
                Me.eJobGroupexecTabField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EReturn() As Bapiret2
            Get
                Return Me.eReturnField
            End Get
            Set
                Me.eReturnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ESuccess() As String
            Get
                Return Me.eSuccessField
            End Get
            Set
                Me.eSuccessField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ETotalZqtapkOri() As Decimal
            Get
                Return Me.eTotalZqtapkOriField
            End Get
            Set
                Me.eTotalZqtapkOriField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ZwmsGetJobGroupExecInfoCompletedEventHandler(ByVal sender As Object, ByVal e As ZwmsGetJobGroupExecInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZwmsGetJobGroupExecInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZwmsGetJobGroupExecInfoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZwmsGetJobGroupExecInfoResponse)
            End Get
        End Property
    End Class
End Namespace
