'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
'
Namespace WS_MB_EXEC_WM_WMS_TO
    
    'CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZWS_MB_EXEC_WM_WMS_TO", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZWS_MB_EXEC_WM_WMS_TO
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZwmMbExecWmWmsToOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WM_Win_PanariaUSA.My.MySettings.Default.WM_Win_PanariaUSA_WS_MB_EXEC_WM_WMS_TO_ZWS_MB_EXEC_WM_WMS_TO
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZwmMbExecWmWmsToCompleted As ZwmMbExecWmWmsToCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWS_MB_EXEC_WM_WMS_TO:ZwmMbExecW"& _ 
            "mWmsToRequest", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZwmMbExecWmWmsTo(<System.Xml.Serialization.XmlElementAttribute("ZwmMbExecWmWmsTo", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ByVal ZwmMbExecWmWmsTo1 As ZwmMbExecWmWmsTo) As <System.Xml.Serialization.XmlElementAttribute("ZwmMbExecWmWmsToResponse", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ZwmMbExecWmWmsToResponse
            Dim results() As Object = Me.Invoke("ZwmMbExecWmWmsTo", New Object() {ZwmMbExecWmWmsTo1})
            Return CType(results(0),ZwmMbExecWmWmsToResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZwmMbExecWmWmsToAsync(ByVal ZwmMbExecWmWmsTo1 As ZwmMbExecWmWmsTo)
            Me.ZwmMbExecWmWmsToAsync(ZwmMbExecWmWmsTo1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZwmMbExecWmWmsToAsync(ByVal ZwmMbExecWmWmsTo1 As ZwmMbExecWmWmsTo, ByVal userState As Object)
            If (Me.ZwmMbExecWmWmsToOperationCompleted Is Nothing) Then
                Me.ZwmMbExecWmWmsToOperationCompleted = AddressOf Me.OnZwmMbExecWmWmsToOperationCompleted
            End If
            Me.InvokeAsync("ZwmMbExecWmWmsTo", New Object() {ZwmMbExecWmWmsTo1}, Me.ZwmMbExecWmWmsToOperationCompleted, userState)
        End Sub
        
        Private Sub OnZwmMbExecWmWmsToOperationCompleted(ByVal arg As Object)
            If (Not (Me.ZwmMbExecWmWmsToCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZwmMbExecWmWmsToCompleted(Me, New ZwmMbExecWmWmsToCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmMbExecWmWmsTo
        
        Private iAbladField As String
        
        Private iAltmeField As String
        
        Private iAnfmeField As Decimal
        
        Private iBemActDurataField As Integer
        
        Private iBemActDurataFieldSpecified As Boolean
        
        Private iBemActEnDtField As String
        
        Private iBemActEnTmField As String
        
        Private iBemActStDtField As String
        
        Private iBemActStTmField As String
        
        Private iBenumField As String
        
        Private iBestqField As String
        
        Private iBetypField As String
        
        Private iBwlvsField As String
        
        Private iChargField As String
        
        Private iElaborationTypeField As String
        
        Private iEnableDebugField As String
        
        Private iLanguageField As String
        
        Private iLetypField As String
        
        Private iLgnumField As String
        
        Private iLgortField As String
        
        Private iLgtypSpuntaField As String
        
        Private iMatnrField As String
        
        Private iMblnrField As String
        
        Private iMessageIdField As String
        
        Private iMjahrField As String
        
        Private iNlberField As String
        
        Private iNlenrField As String
        
        Private iNlplaField As String
        
        Private iNltypField As String
        
        Private iNpposField As String
        
        Private iReceiverIdField As String
        
        Private iSenderIdField As String
        
        Private iSobkzField As String
        
        Private iSonumField As String
        
        Private iSquitField As String
        
        Private iTbnumField As String
        
        Private iTbposField As String
        
        Private iTestrunField As String
        
        Private iUbicaProduzioneField As String
        
        Private iUserIdField As String
        
        Private iUseridRfField As String
        
        Private iVlberField As String
        
        Private iVlenrField As String
        
        Private iVlplaField As String
        
        Private iVlqnrField As String
        
        Private iVltypField As String
        
        Private iVpposField As String
        
        Private iWerksField As String
        
        Private iZeileField As String
        
        Private iZemDaProdField As String
        
        Private iZwmsIdOperationsField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IAblad() As String
            Get
                Return Me.iAbladField
            End Get
            Set
                Me.iAbladField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IAltme() As String
            Get
                Return Me.iAltmeField
            End Get
            Set
                Me.iAltmeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IAnfme() As Decimal
            Get
                Return Me.iAnfmeField
            End Get
            Set
                Me.iAnfmeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IBemActDurata() As Integer
            Get
                Return Me.iBemActDurataField
            End Get
            Set
                Me.iBemActDurataField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property IBemActDurataSpecified() As Boolean
            Get
                Return Me.iBemActDurataFieldSpecified
            End Get
            Set
                Me.iBemActDurataFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IBemActEnDt() As String
            Get
                Return Me.iBemActEnDtField
            End Get
            Set
                Me.iBemActEnDtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IBemActEnTm() As String
            Get
                Return Me.iBemActEnTmField
            End Get
            Set
                Me.iBemActEnTmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IBemActStDt() As String
            Get
                Return Me.iBemActStDtField
            End Get
            Set
                Me.iBemActStDtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IBemActStTm() As String
            Get
                Return Me.iBemActStTmField
            End Get
            Set
                Me.iBemActStTmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IBenum() As String
            Get
                Return Me.iBenumField
            End Get
            Set
                Me.iBenumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IBestq() As String
            Get
                Return Me.iBestqField
            End Get
            Set
                Me.iBestqField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IBetyp() As String
            Get
                Return Me.iBetypField
            End Get
            Set
                Me.iBetypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IBwlvs() As String
            Get
                Return Me.iBwlvsField
            End Get
            Set
                Me.iBwlvsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ICharg() As String
            Get
                Return Me.iChargField
            End Get
            Set
                Me.iChargField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IElaborationType() As String
            Get
                Return Me.iElaborationTypeField
            End Get
            Set
                Me.iElaborationTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IEnableDebug() As String
            Get
                Return Me.iEnableDebugField
            End Get
            Set
                Me.iEnableDebugField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ILanguage() As String
            Get
                Return Me.iLanguageField
            End Get
            Set
                Me.iLanguageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ILetyp() As String
            Get
                Return Me.iLetypField
            End Get
            Set
                Me.iLetypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ILgnum() As String
            Get
                Return Me.iLgnumField
            End Get
            Set
                Me.iLgnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ILgort() As String
            Get
                Return Me.iLgortField
            End Get
            Set
                Me.iLgortField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ILgtypSpunta() As String
            Get
                Return Me.iLgtypSpuntaField
            End Get
            Set
                Me.iLgtypSpuntaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IMatnr() As String
            Get
                Return Me.iMatnrField
            End Get
            Set
                Me.iMatnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IMblnr() As String
            Get
                Return Me.iMblnrField
            End Get
            Set
                Me.iMblnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IMessageId() As String
            Get
                Return Me.iMessageIdField
            End Get
            Set
                Me.iMessageIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IMjahr() As String
            Get
                Return Me.iMjahrField
            End Get
            Set
                Me.iMjahrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property INlber() As String
            Get
                Return Me.iNlberField
            End Get
            Set
                Me.iNlberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property INlenr() As String
            Get
                Return Me.iNlenrField
            End Get
            Set
                Me.iNlenrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property INlpla() As String
            Get
                Return Me.iNlplaField
            End Get
            Set
                Me.iNlplaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property INltyp() As String
            Get
                Return Me.iNltypField
            End Get
            Set
                Me.iNltypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property INppos() As String
            Get
                Return Me.iNpposField
            End Get
            Set
                Me.iNpposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IReceiverId() As String
            Get
                Return Me.iReceiverIdField
            End Get
            Set
                Me.iReceiverIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ISenderId() As String
            Get
                Return Me.iSenderIdField
            End Get
            Set
                Me.iSenderIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ISobkz() As String
            Get
                Return Me.iSobkzField
            End Get
            Set
                Me.iSobkzField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ISonum() As String
            Get
                Return Me.iSonumField
            End Get
            Set
                Me.iSonumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ISquit() As String
            Get
                Return Me.iSquitField
            End Get
            Set
                Me.iSquitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITbnum() As String
            Get
                Return Me.iTbnumField
            End Get
            Set
                Me.iTbnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITbpos() As String
            Get
                Return Me.iTbposField
            End Get
            Set
                Me.iTbposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITestrun() As String
            Get
                Return Me.iTestrunField
            End Get
            Set
                Me.iTestrunField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IUbicaProduzione() As String
            Get
                Return Me.iUbicaProduzioneField
            End Get
            Set
                Me.iUbicaProduzioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IUserId() As String
            Get
                Return Me.iUserIdField
            End Get
            Set
                Me.iUserIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IUseridRf() As String
            Get
                Return Me.iUseridRfField
            End Get
            Set
                Me.iUseridRfField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IVlber() As String
            Get
                Return Me.iVlberField
            End Get
            Set
                Me.iVlberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IVlenr() As String
            Get
                Return Me.iVlenrField
            End Get
            Set
                Me.iVlenrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IVlpla() As String
            Get
                Return Me.iVlplaField
            End Get
            Set
                Me.iVlplaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IVlqnr() As String
            Get
                Return Me.iVlqnrField
            End Get
            Set
                Me.iVlqnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IVltyp() As String
            Get
                Return Me.iVltypField
            End Get
            Set
                Me.iVltypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IVppos() As String
            Get
                Return Me.iVpposField
            End Get
            Set
                Me.iVpposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IWerks() As String
            Get
                Return Me.iWerksField
            End Get
            Set
                Me.iWerksField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IZeile() As String
            Get
                Return Me.iZeileField
            End Get
            Set
                Me.iZeileField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IZemDaProd() As String
            Get
                Return Me.iZemDaProdField
            End Get
            Set
                Me.iZemDaProdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IZwmsIdOperations() As String
            Get
                Return Me.iZwmsIdOperationsField
            End Get
            Set
                Me.iZwmsIdOperationsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class Ltap
        
        Private mandtField As String
        
        Private lgnumField As String
        
        Private tanumField As String
        
        Private taposField As String
        
        Private tbposField As String
        
        Private posnrField As String
        
        Private matnrField As String
        
        Private werksField As String
        
        Private chargField As String
        
        Private bestqField As String
        
        Private sobkzField As String
        
        Private sonumField As String
        
        Private stoffField As String
        
        Private meinsField As String
        
        Private altmeField As String
        
        Private umrezField As Decimal
        
        Private umrenField As Decimal
        
        Private letypField As String
        
        Private kzfehField As String
        
        Private lanumField As String
        
        Private kzquiField As String
        
        Private kznkoField As String
        
        Private nulkoField As String
        
        Private kzinvField As String
        
        Private ivnumField As String
        
        Private pquitField As String
        
        Private qdatuField As String
        
        Private qzeitField As String
        
        Private qnameField As String
        
        Private brgewField As Decimal
        
        Private geweiField As String
        
        Private mbposField As String
        
        Private wempfField As String
        
        Private abladField As String
        
        Private wdatuField As String
        
        Private wenumField As String
        
        Private weposField As String
        
        Private zeugnField As String
        
        Private ldestField As String
        
        Private vorgaField As String
        
        Private vltypField As String
        
        Private vlberField As String
        
        Private vlplaField As String
        
        Private vkdynField As String
        
        Private vpposField As String
        
        Private vanzlField As Decimal
        
        Private vanbrField As String
        
        Private vsolmField As Decimal
        
        Private vistmField As Decimal
        
        Private vdifmField As Decimal
        
        Private vsolaField As Decimal
        
        Private vistaField As Decimal
        
        Private vdifaField As Decimal
        
        Private vlqnrField As String
        
        Private vappcField As String
        
        Private nltypField As String
        
        Private nlberField As String
        
        Private nlplaField As String
        
        Private nkdynField As String
        
        Private npposField As String
        
        Private nanzlField As Decimal
        
        Private nanbrField As String
        
        Private nsolmField As Decimal
        
        Private nistmField As Decimal
        
        Private ndifmField As Decimal
        
        Private nsolaField As Decimal
        
        Private nistaField As Decimal
        
        Private ndifaField As Decimal
        
        Private nlqnrField As String
        
        Private nappcField As String
        
        Private rltypField As String
        
        Private rlberField As String
        
        Private rlplaField As String
        
        Private rpposField As String
        
        Private rsolmField As Decimal
        
        Private ristmField As Decimal
        
        Private rdifmField As Decimal
        
        Private rsolaField As Decimal
        
        Private ristaField As Decimal
        
        Private rdifaField As Decimal
        
        Private rlqnrField As String
        
        Private rappcField As String
        
        Private dltypField As String
        
        Private dlplaField As String
        
        Private dlqnrField As String
        
        Private dmengField As Decimal
        
        Private dmenaField As Decimal
        
        Private kzdifField As String
        
        Private maktxField As String
        
        Private druckField As String
        
        Private vlenrField As String
        
        Private nlenrField As String
        
        Private dlenrField As String
        
        Private vlestField As String
        
        Private nlestField As String
        
        Private lelasField As String
        
        Private homveField As String
        
        Private postyField As String
        
        Private orposField As String
        
        Private vsummField As String
        
        Private vblchField As String
        
        Private nsummField As String
        
        Private nblchField As String
        
        Private rsposField As String
        
        Private vfdatField As String
        
        Private vkapvField As Decimal
        
        Private vkapaField As String
        
        Private nkapaField As String
        
        Private rkapaField As String
        
        Private kzsubField As String
        
        Private qplosField As String
        
        Private qploaField As String
        
        Private kzstiField As String
        
        Private rsartField As String
        
        Private kzechField As String
        
        Private koberField As String
        
        Private lgortField As String
        
        Private solpoField As Decimal
        
        Private zeieiField As String
        
        Private l2skrField As String
        
        Private volumField As Decimal
        
        Private volehField As String
        
        Private kzbefField As String
        
        Private imrelField As String
        
        Private nwirmField As Decimal
        
        Private wirmeField As String
        
        Private npleiField As String
        
        Private kbnkzField As String
        
        Private stoanField As String
        
        Private kgvnqField As String
        
        Private pvquiField As String
        
        Private edatuField As String
        
        Private ezeitField As String
        
        Private enameField As String
        
        Private kzfmeField As String
        
        Private qusubField As String
        
        Private fhutaField As String
        
        Private vnestField As String
        
        Private vhilmField As String
        
        Private vdummField As String
        
        Private ndummField As String
        
        Private vseriField As String
        
        Private hupikField As String
        
        Private nxidvField As String
        
        Private nolisField As String
        
        Private npipoField As String
        
        Private piparField As String
        
        Private pckpfField As String
        
        Private kztrmField As String
        
        Private passdField As String
        
        Private vbelnField As String
        
        Private kzxdkField As String
        
        Private kzvasField As String
        
        Private fromInspGuidField() As Byte
        
        Private toInspGuidField() As Byte
        
        Private diffInspGuidField() As Byte
        
        Private returnInspGuidField() As Byte
        
        Private dcnumField As String
        
        Private zrstgField As String
        
        Private tovasField As String
        
        Private sgtScatField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgnum() As String
            Get
                Return Me.lgnumField
            End Get
            Set
                Me.lgnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tanum() As String
            Get
                Return Me.tanumField
            End Get
            Set
                Me.tanumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tapos() As String
            Get
                Return Me.taposField
            End Get
            Set
                Me.taposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tbpos() As String
            Get
                Return Me.tbposField
            End Get
            Set
                Me.tbposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Posnr() As String
            Get
                Return Me.posnrField
            End Get
            Set
                Me.posnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Matnr() As String
            Get
                Return Me.matnrField
            End Get
            Set
                Me.matnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Werks() As String
            Get
                Return Me.werksField
            End Get
            Set
                Me.werksField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Charg() As String
            Get
                Return Me.chargField
            End Get
            Set
                Me.chargField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Bestq() As String
            Get
                Return Me.bestqField
            End Get
            Set
                Me.bestqField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sobkz() As String
            Get
                Return Me.sobkzField
            End Get
            Set
                Me.sobkzField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sonum() As String
            Get
                Return Me.sonumField
            End Get
            Set
                Me.sonumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Stoff() As String
            Get
                Return Me.stoffField
            End Get
            Set
                Me.stoffField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Meins() As String
            Get
                Return Me.meinsField
            End Get
            Set
                Me.meinsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Altme() As String
            Get
                Return Me.altmeField
            End Get
            Set
                Me.altmeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Umrez() As Decimal
            Get
                Return Me.umrezField
            End Get
            Set
                Me.umrezField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Umren() As Decimal
            Get
                Return Me.umrenField
            End Get
            Set
                Me.umrenField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Letyp() As String
            Get
                Return Me.letypField
            End Get
            Set
                Me.letypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzfeh() As String
            Get
                Return Me.kzfehField
            End Get
            Set
                Me.kzfehField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lanum() As String
            Get
                Return Me.lanumField
            End Get
            Set
                Me.lanumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzqui() As String
            Get
                Return Me.kzquiField
            End Get
            Set
                Me.kzquiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kznko() As String
            Get
                Return Me.kznkoField
            End Get
            Set
                Me.kznkoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nulko() As String
            Get
                Return Me.nulkoField
            End Get
            Set
                Me.nulkoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzinv() As String
            Get
                Return Me.kzinvField
            End Get
            Set
                Me.kzinvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ivnum() As String
            Get
                Return Me.ivnumField
            End Get
            Set
                Me.ivnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Pquit() As String
            Get
                Return Me.pquitField
            End Get
            Set
                Me.pquitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Qdatu() As String
            Get
                Return Me.qdatuField
            End Get
            Set
                Me.qdatuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Qzeit() As String
            Get
                Return Me.qzeitField
            End Get
            Set
                Me.qzeitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Qname() As String
            Get
                Return Me.qnameField
            End Get
            Set
                Me.qnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Brgew() As Decimal
            Get
                Return Me.brgewField
            End Get
            Set
                Me.brgewField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Gewei() As String
            Get
                Return Me.geweiField
            End Get
            Set
                Me.geweiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mbpos() As String
            Get
                Return Me.mbposField
            End Get
            Set
                Me.mbposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Wempf() As String
            Get
                Return Me.wempfField
            End Get
            Set
                Me.wempfField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ablad() As String
            Get
                Return Me.abladField
            End Get
            Set
                Me.abladField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Wdatu() As String
            Get
                Return Me.wdatuField
            End Get
            Set
                Me.wdatuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Wenum() As String
            Get
                Return Me.wenumField
            End Get
            Set
                Me.wenumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Wepos() As String
            Get
                Return Me.weposField
            End Get
            Set
                Me.weposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zeugn() As String
            Get
                Return Me.zeugnField
            End Get
            Set
                Me.zeugnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ldest() As String
            Get
                Return Me.ldestField
            End Get
            Set
                Me.ldestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vorga() As String
            Get
                Return Me.vorgaField
            End Get
            Set
                Me.vorgaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vltyp() As String
            Get
                Return Me.vltypField
            End Get
            Set
                Me.vltypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vlber() As String
            Get
                Return Me.vlberField
            End Get
            Set
                Me.vlberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vlpla() As String
            Get
                Return Me.vlplaField
            End Get
            Set
                Me.vlplaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vkdyn() As String
            Get
                Return Me.vkdynField
            End Get
            Set
                Me.vkdynField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vppos() As String
            Get
                Return Me.vpposField
            End Get
            Set
                Me.vpposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vanzl() As Decimal
            Get
                Return Me.vanzlField
            End Get
            Set
                Me.vanzlField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vanbr() As String
            Get
                Return Me.vanbrField
            End Get
            Set
                Me.vanbrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vsolm() As Decimal
            Get
                Return Me.vsolmField
            End Get
            Set
                Me.vsolmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vistm() As Decimal
            Get
                Return Me.vistmField
            End Get
            Set
                Me.vistmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vdifm() As Decimal
            Get
                Return Me.vdifmField
            End Get
            Set
                Me.vdifmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vsola() As Decimal
            Get
                Return Me.vsolaField
            End Get
            Set
                Me.vsolaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vista() As Decimal
            Get
                Return Me.vistaField
            End Get
            Set
                Me.vistaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vdifa() As Decimal
            Get
                Return Me.vdifaField
            End Get
            Set
                Me.vdifaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vlqnr() As String
            Get
                Return Me.vlqnrField
            End Get
            Set
                Me.vlqnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vappc() As String
            Get
                Return Me.vappcField
            End Get
            Set
                Me.vappcField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nltyp() As String
            Get
                Return Me.nltypField
            End Get
            Set
                Me.nltypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nlber() As String
            Get
                Return Me.nlberField
            End Get
            Set
                Me.nlberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nlpla() As String
            Get
                Return Me.nlplaField
            End Get
            Set
                Me.nlplaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nkdyn() As String
            Get
                Return Me.nkdynField
            End Get
            Set
                Me.nkdynField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nppos() As String
            Get
                Return Me.npposField
            End Get
            Set
                Me.npposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nanzl() As Decimal
            Get
                Return Me.nanzlField
            End Get
            Set
                Me.nanzlField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nanbr() As String
            Get
                Return Me.nanbrField
            End Get
            Set
                Me.nanbrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nsolm() As Decimal
            Get
                Return Me.nsolmField
            End Get
            Set
                Me.nsolmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nistm() As Decimal
            Get
                Return Me.nistmField
            End Get
            Set
                Me.nistmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ndifm() As Decimal
            Get
                Return Me.ndifmField
            End Get
            Set
                Me.ndifmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nsola() As Decimal
            Get
                Return Me.nsolaField
            End Get
            Set
                Me.nsolaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nista() As Decimal
            Get
                Return Me.nistaField
            End Get
            Set
                Me.nistaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ndifa() As Decimal
            Get
                Return Me.ndifaField
            End Get
            Set
                Me.ndifaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nlqnr() As String
            Get
                Return Me.nlqnrField
            End Get
            Set
                Me.nlqnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nappc() As String
            Get
                Return Me.nappcField
            End Get
            Set
                Me.nappcField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rltyp() As String
            Get
                Return Me.rltypField
            End Get
            Set
                Me.rltypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rlber() As String
            Get
                Return Me.rlberField
            End Get
            Set
                Me.rlberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rlpla() As String
            Get
                Return Me.rlplaField
            End Get
            Set
                Me.rlplaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rppos() As String
            Get
                Return Me.rpposField
            End Get
            Set
                Me.rpposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rsolm() As Decimal
            Get
                Return Me.rsolmField
            End Get
            Set
                Me.rsolmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ristm() As Decimal
            Get
                Return Me.ristmField
            End Get
            Set
                Me.ristmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rdifm() As Decimal
            Get
                Return Me.rdifmField
            End Get
            Set
                Me.rdifmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rsola() As Decimal
            Get
                Return Me.rsolaField
            End Get
            Set
                Me.rsolaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rista() As Decimal
            Get
                Return Me.ristaField
            End Get
            Set
                Me.ristaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rdifa() As Decimal
            Get
                Return Me.rdifaField
            End Get
            Set
                Me.rdifaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rlqnr() As String
            Get
                Return Me.rlqnrField
            End Get
            Set
                Me.rlqnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rappc() As String
            Get
                Return Me.rappcField
            End Get
            Set
                Me.rappcField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Dltyp() As String
            Get
                Return Me.dltypField
            End Get
            Set
                Me.dltypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Dlpla() As String
            Get
                Return Me.dlplaField
            End Get
            Set
                Me.dlplaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Dlqnr() As String
            Get
                Return Me.dlqnrField
            End Get
            Set
                Me.dlqnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Dmeng() As Decimal
            Get
                Return Me.dmengField
            End Get
            Set
                Me.dmengField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Dmena() As Decimal
            Get
                Return Me.dmenaField
            End Get
            Set
                Me.dmenaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzdif() As String
            Get
                Return Me.kzdifField
            End Get
            Set
                Me.kzdifField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Maktx() As String
            Get
                Return Me.maktxField
            End Get
            Set
                Me.maktxField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Druck() As String
            Get
                Return Me.druckField
            End Get
            Set
                Me.druckField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vlenr() As String
            Get
                Return Me.vlenrField
            End Get
            Set
                Me.vlenrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nlenr() As String
            Get
                Return Me.nlenrField
            End Get
            Set
                Me.nlenrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Dlenr() As String
            Get
                Return Me.dlenrField
            End Get
            Set
                Me.dlenrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vlest() As String
            Get
                Return Me.vlestField
            End Get
            Set
                Me.vlestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nlest() As String
            Get
                Return Me.nlestField
            End Get
            Set
                Me.nlestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lelas() As String
            Get
                Return Me.lelasField
            End Get
            Set
                Me.lelasField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Homve() As String
            Get
                Return Me.homveField
            End Get
            Set
                Me.homveField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Posty() As String
            Get
                Return Me.postyField
            End Get
            Set
                Me.postyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Orpos() As String
            Get
                Return Me.orposField
            End Get
            Set
                Me.orposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vsumm() As String
            Get
                Return Me.vsummField
            End Get
            Set
                Me.vsummField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vblch() As String
            Get
                Return Me.vblchField
            End Get
            Set
                Me.vblchField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nsumm() As String
            Get
                Return Me.nsummField
            End Get
            Set
                Me.nsummField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nblch() As String
            Get
                Return Me.nblchField
            End Get
            Set
                Me.nblchField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rspos() As String
            Get
                Return Me.rsposField
            End Get
            Set
                Me.rsposField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vfdat() As String
            Get
                Return Me.vfdatField
            End Get
            Set
                Me.vfdatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vkapv() As Decimal
            Get
                Return Me.vkapvField
            End Get
            Set
                Me.vkapvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vkapa() As String
            Get
                Return Me.vkapaField
            End Get
            Set
                Me.vkapaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nkapa() As String
            Get
                Return Me.nkapaField
            End Get
            Set
                Me.nkapaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rkapa() As String
            Get
                Return Me.rkapaField
            End Get
            Set
                Me.rkapaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzsub() As String
            Get
                Return Me.kzsubField
            End Get
            Set
                Me.kzsubField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Qplos() As String
            Get
                Return Me.qplosField
            End Get
            Set
                Me.qplosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Qploa() As String
            Get
                Return Me.qploaField
            End Get
            Set
                Me.qploaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzsti() As String
            Get
                Return Me.kzstiField
            End Get
            Set
                Me.kzstiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rsart() As String
            Get
                Return Me.rsartField
            End Get
            Set
                Me.rsartField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzech() As String
            Get
                Return Me.kzechField
            End Get
            Set
                Me.kzechField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kober() As String
            Get
                Return Me.koberField
            End Get
            Set
                Me.koberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lgort() As String
            Get
                Return Me.lgortField
            End Get
            Set
                Me.lgortField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Solpo() As Decimal
            Get
                Return Me.solpoField
            End Get
            Set
                Me.solpoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zeiei() As String
            Get
                Return Me.zeieiField
            End Get
            Set
                Me.zeieiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property L2skr() As String
            Get
                Return Me.l2skrField
            End Get
            Set
                Me.l2skrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Volum() As Decimal
            Get
                Return Me.volumField
            End Get
            Set
                Me.volumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Voleh() As String
            Get
                Return Me.volehField
            End Get
            Set
                Me.volehField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzbef() As String
            Get
                Return Me.kzbefField
            End Get
            Set
                Me.kzbefField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Imrel() As String
            Get
                Return Me.imrelField
            End Get
            Set
                Me.imrelField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nwirm() As Decimal
            Get
                Return Me.nwirmField
            End Get
            Set
                Me.nwirmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Wirme() As String
            Get
                Return Me.wirmeField
            End Get
            Set
                Me.wirmeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nplei() As String
            Get
                Return Me.npleiField
            End Get
            Set
                Me.npleiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kbnkz() As String
            Get
                Return Me.kbnkzField
            End Get
            Set
                Me.kbnkzField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Stoan() As String
            Get
                Return Me.stoanField
            End Get
            Set
                Me.stoanField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kgvnq() As String
            Get
                Return Me.kgvnqField
            End Get
            Set
                Me.kgvnqField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Pvqui() As String
            Get
                Return Me.pvquiField
            End Get
            Set
                Me.pvquiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Edatu() As String
            Get
                Return Me.edatuField
            End Get
            Set
                Me.edatuField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ezeit() As String
            Get
                Return Me.ezeitField
            End Get
            Set
                Me.ezeitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ename() As String
            Get
                Return Me.enameField
            End Get
            Set
                Me.enameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzfme() As String
            Get
                Return Me.kzfmeField
            End Get
            Set
                Me.kzfmeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Qusub() As String
            Get
                Return Me.qusubField
            End Get
            Set
                Me.qusubField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Fhuta() As String
            Get
                Return Me.fhutaField
            End Get
            Set
                Me.fhutaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vnest() As String
            Get
                Return Me.vnestField
            End Get
            Set
                Me.vnestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vhilm() As String
            Get
                Return Me.vhilmField
            End Get
            Set
                Me.vhilmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vdumm() As String
            Get
                Return Me.vdummField
            End Get
            Set
                Me.vdummField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ndumm() As String
            Get
                Return Me.ndummField
            End Get
            Set
                Me.ndummField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vseri() As String
            Get
                Return Me.vseriField
            End Get
            Set
                Me.vseriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Hupik() As String
            Get
                Return Me.hupikField
            End Get
            Set
                Me.hupikField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nxidv() As String
            Get
                Return Me.nxidvField
            End Get
            Set
                Me.nxidvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nolis() As String
            Get
                Return Me.nolisField
            End Get
            Set
                Me.nolisField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Npipo() As String
            Get
                Return Me.npipoField
            End Get
            Set
                Me.npipoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Pipar() As String
            Get
                Return Me.piparField
            End Get
            Set
                Me.piparField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Pckpf() As String
            Get
                Return Me.pckpfField
            End Get
            Set
                Me.pckpfField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kztrm() As String
            Get
                Return Me.kztrmField
            End Get
            Set
                Me.kztrmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Passd() As String
            Get
                Return Me.passdField
            End Get
            Set
                Me.passdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vbeln() As String
            Get
                Return Me.vbelnField
            End Get
            Set
                Me.vbelnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzxdk() As String
            Get
                Return Me.kzxdkField
            End Get
            Set
                Me.kzxdkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Kzvas() As String
            Get
                Return Me.kzvasField
            End Get
            Set
                Me.kzvasField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property FromInspGuid() As Byte()
            Get
                Return Me.fromInspGuidField
            End Get
            Set
                Me.fromInspGuidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property ToInspGuid() As Byte()
            Get
                Return Me.toInspGuidField
            End Get
            Set
                Me.toInspGuidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property DiffInspGuid() As Byte()
            Get
                Return Me.diffInspGuidField
            End Get
            Set
                Me.diffInspGuidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property ReturnInspGuid() As Byte()
            Get
                Return Me.returnInspGuidField
            End Get
            Set
                Me.returnInspGuidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Dcnum() As String
            Get
                Return Me.dcnumField
            End Get
            Set
                Me.dcnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zrstg() As String
            Get
                Return Me.zrstgField
            End Get
            Set
                Me.zrstgField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tovas() As String
            Get
                Return Me.tovasField
            End Get
            Set
                Me.tovasField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SgtScat() As String
            Get
                Return Me.sgtScatField
            End Get
            Set
                Me.sgtScatField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmMbExecWmWmsToResponse
        
        Private eErrorCodeField As String
        
        Private eErrorDescriptionField As String
        
        Private eErrorSubrcField As Integer
        
        Private eLtapField As Ltap
        
        Private eSuccessField As String
        
        Private eTanumField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorCode() As String
            Get
                Return Me.eErrorCodeField
            End Get
            Set
                Me.eErrorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorDescription() As String
            Get
                Return Me.eErrorDescriptionField
            End Get
            Set
                Me.eErrorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorSubrc() As Integer
            Get
                Return Me.eErrorSubrcField
            End Get
            Set
                Me.eErrorSubrcField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ELtap() As Ltap
            Get
                Return Me.eLtapField
            End Get
            Set
                Me.eLtapField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ESuccess() As String
            Get
                Return Me.eSuccessField
            End Get
            Set
                Me.eSuccessField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ETanum() As String
            Get
                Return Me.eTanumField
            End Get
            Set
                Me.eTanumField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ZwmMbExecWmWmsToCompletedEventHandler(ByVal sender As Object, ByVal e As ZwmMbExecWmWmsToCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZwmMbExecWmWmsToCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZwmMbExecWmWmsToResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZwmMbExecWmWmsToResponse)
            End Get
        End Property
    End Class
End Namespace
