'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
'
Namespace WS_CHECK_JOBGROUP_OK_X_CLOSE
    
    'CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZWS_CHECK_JOBGROUP_OK_X_CLOSE", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZWS_CHECK_JOBGROUP_OK_X_CLOSE
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZwmsCheckJobgroupOkXCloseOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WM_Win_PanariaUSA.My.MySettings.Default.WM_Win_PanariaUSA_WS_CHECK_JOBGROUP_OK_X_CLOSE_ZWS_CHECK_JOBGROUP_OK_X_CLOSE
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZwmsCheckJobgroupOkXCloseCompleted As ZwmsCheckJobgroupOkXCloseCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWS_CHECK_JOBGROUP_OK_X_CLOSE:Zw"& _ 
            "msCheckJobgroupOkXCloseRequest", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZwmsCheckJobgroupOkXClose(<System.Xml.Serialization.XmlElementAttribute("ZwmsCheckJobgroupOkXClose", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ByVal ZwmsCheckJobgroupOkXClose1 As ZwmsCheckJobgroupOkXClose) As <System.Xml.Serialization.XmlElementAttribute("ZwmsCheckJobgroupOkXCloseResponse", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ZwmsCheckJobgroupOkXCloseResponse
            Dim results() As Object = Me.Invoke("ZwmsCheckJobgroupOkXClose", New Object() {ZwmsCheckJobgroupOkXClose1})
            Return CType(results(0),ZwmsCheckJobgroupOkXCloseResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZwmsCheckJobgroupOkXCloseAsync(ByVal ZwmsCheckJobgroupOkXClose1 As ZwmsCheckJobgroupOkXClose)
            Me.ZwmsCheckJobgroupOkXCloseAsync(ZwmsCheckJobgroupOkXClose1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZwmsCheckJobgroupOkXCloseAsync(ByVal ZwmsCheckJobgroupOkXClose1 As ZwmsCheckJobgroupOkXClose, ByVal userState As Object)
            If (Me.ZwmsCheckJobgroupOkXCloseOperationCompleted Is Nothing) Then
                Me.ZwmsCheckJobgroupOkXCloseOperationCompleted = AddressOf Me.OnZwmsCheckJobgroupOkXCloseOperationCompleted
            End If
            Me.InvokeAsync("ZwmsCheckJobgroupOkXClose", New Object() {ZwmsCheckJobgroupOkXClose1}, Me.ZwmsCheckJobgroupOkXCloseOperationCompleted, userState)
        End Sub
        
        Private Sub OnZwmsCheckJobgroupOkXCloseOperationCompleted(ByVal arg As Object)
            If (Not (Me.ZwmsCheckJobgroupOkXCloseCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZwmsCheckJobgroupOkXCloseCompleted(Me, New ZwmsCheckJobgroupOkXCloseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmsCheckJobgroupOkXClose
        
        Private iEnableDebugField As String
        
        Private iSprasField As String
        
        Private iZnrWmsJobsgrpField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IEnableDebug() As String
            Get
                Return Me.iEnableDebugField
            End Get
            Set
                Me.iEnableDebugField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ISpras() As String
            Get
                Return Me.iSprasField
            End Get
            Set
                Me.iSprasField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IZnrWmsJobsgrp() As String
            Get
                Return Me.iZnrWmsJobsgrpField
            End Get
            Set
                Me.iZnrWmsJobsgrpField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmsJobs
        
        Private mandtField As String
        
        Private znrWmsJobsField As Integer
        
        Private sequenceField As Integer
        
        Private sequencePrintField As Integer
        
        Private execPrintField As String
        
        Private printDoneField As String
        
        Private currentStepField As Byte
        
        Private numStepsTotalField As String
        
        Private dataCreazioneField As String
        
        Private oraCreazioneField As String
        
        Private pickDbtabnameField As String
        
        Private znrpickField As String
        
        Private zpospkField As String
        
        Private vbelnField As String
        
        Private posnrField As String
        
        Private numConsVbelvField As String
        
        Private posConsPosnvField As String
        
        Private znrWmsJobsgrpField As String
        
        Private znrWmsGrpexecField As Integer
        
        Private mblnrField As String
        
        Private mjahrField As String
        
        Private zeileField As String
        
        Private idstatusField As Short
        
        Private idJobsTypeField As String
        
        Private idWmsDevicesField As String
        
        Private prioritaField As Integer
        
        Private urgenteField As String
        
        Private matnrOriField As String
        
        Private werksOriField As String
        
        Private lgortOriField As String
        
        Private chargOriField As String
        
        Private bestqOriField As String
        
        Private sobkzOriField As String
        
        Private sonumOriField As String
        
        Private meinsOriField As String
        
        Private zqtapkOriField As Decimal
        
        Private zqtaPrelBaseField As Decimal
        
        Private udmQtaprMeinsField As String
        
        Private zqtaPrelConsField As Decimal
        
        Private udmQtaprConsField As String
        
        Private zflawmField As String
        
        Private palletInteriField As String
        
        Private scatoleIntereField As String
        
        Private zcarrPropField As String
        
        Private zcarrExecField As String
        
        Private lgnumOriField As String
        
        Private lgtypOriField As String
        
        Private lgplaOriField As String
        
        Private lenumOriField As String
        
        Private lgnumDestField As String
        
        Private lgtypDestField As String
        
        Private lgplaDestField As String
        
        Private lenumDestField As String
        
        Private matnrDestField As String
        
        Private werksDestField As String
        
        Private lgortDestField As String
        
        Private chargDestField As String
        
        Private bestqDestField As String
        
        Private sobkzDestField As String
        
        Private sonumDestField As String
        
        Private lgnumPropOriField As String
        
        Private lgtypPropOriField As String
        
        Private lgplaPropOriField As String
        
        Private okQtaPropOriField As String
        
        Private lgnumPropDestField As String
        
        Private lgtypPropDestField As String
        
        Private lgplaPropDestField As String
        
        Private okQtaPropDestField As String
        
        Private chargTassativaField As String
        
        Private zdocField As String
        
        Private fornitoreLifnrField As String
        
        Private deleField As String
        
        Private memoField As String
        
        Private zzNdisField As String
        
        Private ernamField As String
        
        Private erdatField As String
        
        Private erzeitField As String
        
        Private aenamField As String
        
        Private aedatField As String
        
        Private aezeitField As String
        
        Private dataStartField As String
        
        Private oraStartField As String
        
        Private dataFineField As String
        
        Private oraFineField As String
        
        Private znrWmsJobsOriField As Integer
        
        Private zwmsjobsgrpOriField As String
        
        Private infoPrelievoField As String
        
        Private znrWmsJobsCarField As String
        
        Private ltkzeField As String
        
        Private ltkzaField As String
        
        Private zmatnrChkPronField As String
        
        Private zjobsShippedField As String
        
        Private zjobsShipConsField As String
        
        Private zjobsShipConpField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZnrWmsJobs() As Integer
            Get
                Return Me.znrWmsJobsField
            End Get
            Set
                Me.znrWmsJobsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sequence() As Integer
            Get
                Return Me.sequenceField
            End Get
            Set
                Me.sequenceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SequencePrint() As Integer
            Get
                Return Me.sequencePrintField
            End Get
            Set
                Me.sequencePrintField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ExecPrint() As String
            Get
                Return Me.execPrintField
            End Get
            Set
                Me.execPrintField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PrintDone() As String
            Get
                Return Me.printDoneField
            End Get
            Set
                Me.printDoneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CurrentStep() As Byte
            Get
                Return Me.currentStepField
            End Get
            Set
                Me.currentStepField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NumStepsTotal() As String
            Get
                Return Me.numStepsTotalField
            End Get
            Set
                Me.numStepsTotalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DataCreazione() As String
            Get
                Return Me.dataCreazioneField
            End Get
            Set
                Me.dataCreazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OraCreazione() As String
            Get
                Return Me.oraCreazioneField
            End Get
            Set
                Me.oraCreazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PickDbtabname() As String
            Get
                Return Me.pickDbtabnameField
            End Get
            Set
                Me.pickDbtabnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Znrpick() As String
            Get
                Return Me.znrpickField
            End Get
            Set
                Me.znrpickField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zpospk() As String
            Get
                Return Me.zpospkField
            End Get
            Set
                Me.zpospkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vbeln() As String
            Get
                Return Me.vbelnField
            End Get
            Set
                Me.vbelnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Posnr() As String
            Get
                Return Me.posnrField
            End Get
            Set
                Me.posnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NumConsVbelv() As String
            Get
                Return Me.numConsVbelvField
            End Get
            Set
                Me.numConsVbelvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PosConsPosnv() As String
            Get
                Return Me.posConsPosnvField
            End Get
            Set
                Me.posConsPosnvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZnrWmsJobsgrp() As String
            Get
                Return Me.znrWmsJobsgrpField
            End Get
            Set
                Me.znrWmsJobsgrpField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZnrWmsGrpexec() As Integer
            Get
                Return Me.znrWmsGrpexecField
            End Get
            Set
                Me.znrWmsGrpexecField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mblnr() As String
            Get
                Return Me.mblnrField
            End Get
            Set
                Me.mblnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mjahr() As String
            Get
                Return Me.mjahrField
            End Get
            Set
                Me.mjahrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zeile() As String
            Get
                Return Me.zeileField
            End Get
            Set
                Me.zeileField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idstatus() As Short
            Get
                Return Me.idstatusField
            End Get
            Set
                Me.idstatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IdJobsType() As String
            Get
                Return Me.idJobsTypeField
            End Get
            Set
                Me.idJobsTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IdWmsDevices() As String
            Get
                Return Me.idWmsDevicesField
            End Get
            Set
                Me.idWmsDevicesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Priorita() As Integer
            Get
                Return Me.prioritaField
            End Get
            Set
                Me.prioritaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Urgente() As String
            Get
                Return Me.urgenteField
            End Get
            Set
                Me.urgenteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MatnrOri() As String
            Get
                Return Me.matnrOriField
            End Get
            Set
                Me.matnrOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property WerksOri() As String
            Get
                Return Me.werksOriField
            End Get
            Set
                Me.werksOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgortOri() As String
            Get
                Return Me.lgortOriField
            End Get
            Set
                Me.lgortOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ChargOri() As String
            Get
                Return Me.chargOriField
            End Get
            Set
                Me.chargOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BestqOri() As String
            Get
                Return Me.bestqOriField
            End Get
            Set
                Me.bestqOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SobkzOri() As String
            Get
                Return Me.sobkzOriField
            End Get
            Set
                Me.sobkzOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SonumOri() As String
            Get
                Return Me.sonumOriField
            End Get
            Set
                Me.sonumOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MeinsOri() As String
            Get
                Return Me.meinsOriField
            End Get
            Set
                Me.meinsOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZqtapkOri() As Decimal
            Get
                Return Me.zqtapkOriField
            End Get
            Set
                Me.zqtapkOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZqtaPrelBase() As Decimal
            Get
                Return Me.zqtaPrelBaseField
            End Get
            Set
                Me.zqtaPrelBaseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UdmQtaprMeins() As String
            Get
                Return Me.udmQtaprMeinsField
            End Get
            Set
                Me.udmQtaprMeinsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZqtaPrelCons() As Decimal
            Get
                Return Me.zqtaPrelConsField
            End Get
            Set
                Me.zqtaPrelConsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UdmQtaprCons() As String
            Get
                Return Me.udmQtaprConsField
            End Get
            Set
                Me.udmQtaprConsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zflawm() As String
            Get
                Return Me.zflawmField
            End Get
            Set
                Me.zflawmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PalletInteri() As String
            Get
                Return Me.palletInteriField
            End Get
            Set
                Me.palletInteriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ScatoleIntere() As String
            Get
                Return Me.scatoleIntereField
            End Get
            Set
                Me.scatoleIntereField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZcarrProp() As String
            Get
                Return Me.zcarrPropField
            End Get
            Set
                Me.zcarrPropField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZcarrExec() As String
            Get
                Return Me.zcarrExecField
            End Get
            Set
                Me.zcarrExecField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgnumOri() As String
            Get
                Return Me.lgnumOriField
            End Get
            Set
                Me.lgnumOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgtypOri() As String
            Get
                Return Me.lgtypOriField
            End Get
            Set
                Me.lgtypOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgplaOri() As String
            Get
                Return Me.lgplaOriField
            End Get
            Set
                Me.lgplaOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LenumOri() As String
            Get
                Return Me.lenumOriField
            End Get
            Set
                Me.lenumOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgnumDest() As String
            Get
                Return Me.lgnumDestField
            End Get
            Set
                Me.lgnumDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgtypDest() As String
            Get
                Return Me.lgtypDestField
            End Get
            Set
                Me.lgtypDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgplaDest() As String
            Get
                Return Me.lgplaDestField
            End Get
            Set
                Me.lgplaDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LenumDest() As String
            Get
                Return Me.lenumDestField
            End Get
            Set
                Me.lenumDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MatnrDest() As String
            Get
                Return Me.matnrDestField
            End Get
            Set
                Me.matnrDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property WerksDest() As String
            Get
                Return Me.werksDestField
            End Get
            Set
                Me.werksDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgortDest() As String
            Get
                Return Me.lgortDestField
            End Get
            Set
                Me.lgortDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ChargDest() As String
            Get
                Return Me.chargDestField
            End Get
            Set
                Me.chargDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BestqDest() As String
            Get
                Return Me.bestqDestField
            End Get
            Set
                Me.bestqDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SobkzDest() As String
            Get
                Return Me.sobkzDestField
            End Get
            Set
                Me.sobkzDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SonumDest() As String
            Get
                Return Me.sonumDestField
            End Get
            Set
                Me.sonumDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgnumPropOri() As String
            Get
                Return Me.lgnumPropOriField
            End Get
            Set
                Me.lgnumPropOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgtypPropOri() As String
            Get
                Return Me.lgtypPropOriField
            End Get
            Set
                Me.lgtypPropOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgplaPropOri() As String
            Get
                Return Me.lgplaPropOriField
            End Get
            Set
                Me.lgplaPropOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OkQtaPropOri() As String
            Get
                Return Me.okQtaPropOriField
            End Get
            Set
                Me.okQtaPropOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgnumPropDest() As String
            Get
                Return Me.lgnumPropDestField
            End Get
            Set
                Me.lgnumPropDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgtypPropDest() As String
            Get
                Return Me.lgtypPropDestField
            End Get
            Set
                Me.lgtypPropDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgplaPropDest() As String
            Get
                Return Me.lgplaPropDestField
            End Get
            Set
                Me.lgplaPropDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OkQtaPropDest() As String
            Get
                Return Me.okQtaPropDestField
            End Get
            Set
                Me.okQtaPropDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ChargTassativa() As String
            Get
                Return Me.chargTassativaField
            End Get
            Set
                Me.chargTassativaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zdoc() As String
            Get
                Return Me.zdocField
            End Get
            Set
                Me.zdocField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FornitoreLifnr() As String
            Get
                Return Me.fornitoreLifnrField
            End Get
            Set
                Me.fornitoreLifnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Dele() As String
            Get
                Return Me.deleField
            End Get
            Set
                Me.deleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Memo() As String
            Get
                Return Me.memoField
            End Get
            Set
                Me.memoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZzNdis() As String
            Get
                Return Me.zzNdisField
            End Get
            Set
                Me.zzNdisField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ernam() As String
            Get
                Return Me.ernamField
            End Get
            Set
                Me.ernamField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Erdat() As String
            Get
                Return Me.erdatField
            End Get
            Set
                Me.erdatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Erzeit() As String
            Get
                Return Me.erzeitField
            End Get
            Set
                Me.erzeitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Aenam() As String
            Get
                Return Me.aenamField
            End Get
            Set
                Me.aenamField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Aedat() As String
            Get
                Return Me.aedatField
            End Get
            Set
                Me.aedatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Aezeit() As String
            Get
                Return Me.aezeitField
            End Get
            Set
                Me.aezeitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DataStart() As String
            Get
                Return Me.dataStartField
            End Get
            Set
                Me.dataStartField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OraStart() As String
            Get
                Return Me.oraStartField
            End Get
            Set
                Me.oraStartField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DataFine() As String
            Get
                Return Me.dataFineField
            End Get
            Set
                Me.dataFineField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OraFine() As String
            Get
                Return Me.oraFineField
            End Get
            Set
                Me.oraFineField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZnrWmsJobsOri() As Integer
            Get
                Return Me.znrWmsJobsOriField
            End Get
            Set
                Me.znrWmsJobsOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZwmsjobsgrpOri() As String
            Get
                Return Me.zwmsjobsgrpOriField
            End Get
            Set
                Me.zwmsjobsgrpOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property InfoPrelievo() As String
            Get
                Return Me.infoPrelievoField
            End Get
            Set
                Me.infoPrelievoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZnrWmsJobsCar() As String
            Get
                Return Me.znrWmsJobsCarField
            End Get
            Set
                Me.znrWmsJobsCarField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ltkze() As String
            Get
                Return Me.ltkzeField
            End Get
            Set
                Me.ltkzeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ltkza() As String
            Get
                Return Me.ltkzaField
            End Get
            Set
                Me.ltkzaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZmatnrChkPron() As String
            Get
                Return Me.zmatnrChkPronField
            End Get
            Set
                Me.zmatnrChkPronField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZjobsShipped() As String
            Get
                Return Me.zjobsShippedField
            End Get
            Set
                Me.zjobsShippedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZjobsShipCons() As String
            Get
                Return Me.zjobsShipConsField
            End Get
            Set
                Me.zjobsShipConsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZjobsShipConp() As String
            Get
                Return Me.zjobsShipConpField
            End Get
            Set
                Me.zjobsShipConpField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class Bapiret2
        
        Private typeField As String
        
        Private idField As String
        
        Private numberField As String
        
        Private messageField As String
        
        Private logNoField As String
        
        Private logMsgNoField As String
        
        Private messageV1Field As String
        
        Private messageV2Field As String
        
        Private messageV3Field As String
        
        Private messageV4Field As String
        
        Private parameterField As String
        
        Private rowField As Integer
        
        Private fieldField As String
        
        Private systemField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set(value As String)
                Me.typeField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Number() As String
            Get
                Return Me.numberField
            End Get
            Set(value As String)
                Me.numberField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set(value As String)
                Me.messageField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property LogNo() As String
            Get
                Return Me.logNoField
            End Get
            Set(value As String)
                Me.logNoField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property LogMsgNo() As String
            Get
                Return Me.logMsgNoField
            End Get
            Set(value As String)
                Me.logMsgNoField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV1() As String
            Get
                Return Me.messageV1Field
            End Get
            Set(value As String)
                Me.messageV1Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV2() As String
            Get
                Return Me.messageV2Field
            End Get
            Set(value As String)
                Me.messageV2Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV3() As String
            Get
                Return Me.messageV3Field
            End Get
            Set(value As String)
                Me.messageV3Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV4() As String
            Get
                Return Me.messageV4Field
            End Get
            Set(value As String)
                Me.messageV4Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Parameter() As String
            Get
                Return Me.parameterField
            End Get
            Set(value As String)
                Me.parameterField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Row() As Integer
            Get
                Return Me.rowField
            End Get
            Set(value As Integer)
                Me.rowField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Field() As String
            Get
                Return Me.fieldField
            End Get
            Set(value As String)
                Me.fieldField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property System() As String
            Get
                Return Me.systemField
            End Get
            Set(value As String)
                Me.systemField = Value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmsCheckJobgroupOkXCloseResponse
        
        Private eCheckOkField As String
        
        Private eErrorCodeField As String
        
        Private eErrorDescriptionField As String
        
        Private eErrorSubrcField As Integer
        
        Private eFoundrowsField As Integer
        
        Private eReturnField As Bapiret2
        
        Private eSuccessField As String
        
        Private eZwmsJobsNotOkField As ZwmsJobs
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ECheckOk() As String
            Get
                Return Me.eCheckOkField
            End Get
            Set
                Me.eCheckOkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorCode() As String
            Get
                Return Me.eErrorCodeField
            End Get
            Set
                Me.eErrorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorDescription() As String
            Get
                Return Me.eErrorDescriptionField
            End Get
            Set
                Me.eErrorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorSubrc() As Integer
            Get
                Return Me.eErrorSubrcField
            End Get
            Set
                Me.eErrorSubrcField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EFoundrows() As Integer
            Get
                Return Me.eFoundrowsField
            End Get
            Set
                Me.eFoundrowsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EReturn() As Bapiret2
            Get
                Return Me.eReturnField
            End Get
            Set
                Me.eReturnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ESuccess() As String
            Get
                Return Me.eSuccessField
            End Get
            Set
                Me.eSuccessField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EZwmsJobsNotOk() As ZwmsJobs
            Get
                Return Me.eZwmsJobsNotOkField
            End Get
            Set
                Me.eZwmsJobsNotOkField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ZwmsCheckJobgroupOkXCloseCompletedEventHandler(ByVal sender As Object, ByVal e As ZwmsCheckJobgroupOkXCloseCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZwmsCheckJobgroupOkXCloseCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZwmsCheckJobgroupOkXCloseResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZwmsCheckJobgroupOkXCloseResponse)
            End Get
        End Property
    End Class
End Namespace
