'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
'
Namespace WS_JOB_EM_STEPS_EXECUTED
    
    'CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZWS_JOB_EM_STEPS_EXECUTED", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZWS_JOB_EM_STEPS_EXECUTED
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZwmsJobEmStepsExecutedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WM_Win_PanariaUSA.My.MySettings.Default.WM_Win_PanariaUSA_WS_JOB_EM_STEPS_EXECUTED_ZWS_JOB_EM_STEPS_EXECUTED
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZwmsJobEmStepsExecutedCompleted As ZwmsJobEmStepsExecutedCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWS_JOB_EM_STEPS_EXECUTED:ZwmsJo"& _ 
            "bEmStepsExecutedRequest", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZwmsJobEmStepsExecuted(<System.Xml.Serialization.XmlElementAttribute("ZwmsJobEmStepsExecuted", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ByVal ZwmsJobEmStepsExecuted1 As ZwmsJobEmStepsExecuted) As <System.Xml.Serialization.XmlElementAttribute("ZwmsJobEmStepsExecutedResponse", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ZwmsJobEmStepsExecutedResponse
            Dim results() As Object = Me.Invoke("ZwmsJobEmStepsExecuted", New Object() {ZwmsJobEmStepsExecuted1})
            Return CType(results(0),ZwmsJobEmStepsExecutedResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZwmsJobEmStepsExecutedAsync(ByVal ZwmsJobEmStepsExecuted1 As ZwmsJobEmStepsExecuted)
            Me.ZwmsJobEmStepsExecutedAsync(ZwmsJobEmStepsExecuted1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZwmsJobEmStepsExecutedAsync(ByVal ZwmsJobEmStepsExecuted1 As ZwmsJobEmStepsExecuted, ByVal userState As Object)
            If (Me.ZwmsJobEmStepsExecutedOperationCompleted Is Nothing) Then
                Me.ZwmsJobEmStepsExecutedOperationCompleted = AddressOf Me.OnZwmsJobEmStepsExecutedOperationCompleted
            End If
            Me.InvokeAsync("ZwmsJobEmStepsExecuted", New Object() {ZwmsJobEmStepsExecuted1}, Me.ZwmsJobEmStepsExecutedOperationCompleted, userState)
        End Sub
        
        Private Sub OnZwmsJobEmStepsExecutedOperationCompleted(ByVal arg As Object)
            If (Not (Me.ZwmsJobEmStepsExecutedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZwmsJobEmStepsExecutedCompleted(Me, New ZwmsJobEmStepsExecutedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmsJobEmStepsExecuted
        
        Private iCreateJobsEndedField As String
        
        Private iEnableDebugField As String
        
        Private iFlagStepEndedField As String
        
        Private iGetZwmsJobsRecField As String
        
        Private iGetZwmsJobsStepsRecField As String
        
        Private iIdJobActionField As String
        
        Private iInfoPrelievoField As String
        
        Private iJobsActDurataField As Integer
        
        Private iJobsActDurataFieldSpecified As Boolean
        
        Private iJobsActEnDtField As String
        
        Private iJobsActEnTmField As String
        
        Private iJobsActStDtField As String
        
        Private iJobsActStTmField As String
        
        Private iSprasField As String
        
        Private iUseridRfField As String
        
        Private iZnrWmsJobsField As Integer
        
        Private iZwmsAppVersionField As String
        
        Private iZwmsComputerField As String
        
        Private iZwmsJobsStepField As String
        
        Private iZwmsMatInfoTabField() As ZwmsStepsExecutedMatInfo
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ICreateJobsEnded() As String
            Get
                Return Me.iCreateJobsEndedField
            End Get
            Set
                Me.iCreateJobsEndedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IEnableDebug() As String
            Get
                Return Me.iEnableDebugField
            End Get
            Set
                Me.iEnableDebugField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IFlagStepEnded() As String
            Get
                Return Me.iFlagStepEndedField
            End Get
            Set
                Me.iFlagStepEndedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IGetZwmsJobsRec() As String
            Get
                Return Me.iGetZwmsJobsRecField
            End Get
            Set
                Me.iGetZwmsJobsRecField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IGetZwmsJobsStepsRec() As String
            Get
                Return Me.iGetZwmsJobsStepsRecField
            End Get
            Set
                Me.iGetZwmsJobsStepsRecField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IIdJobAction() As String
            Get
                Return Me.iIdJobActionField
            End Get
            Set
                Me.iIdJobActionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IInfoPrelievo() As String
            Get
                Return Me.iInfoPrelievoField
            End Get
            Set
                Me.iInfoPrelievoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IJobsActDurata() As Integer
            Get
                Return Me.iJobsActDurataField
            End Get
            Set
                Me.iJobsActDurataField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property IJobsActDurataSpecified() As Boolean
            Get
                Return Me.iJobsActDurataFieldSpecified
            End Get
            Set
                Me.iJobsActDurataFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IJobsActEnDt() As String
            Get
                Return Me.iJobsActEnDtField
            End Get
            Set
                Me.iJobsActEnDtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IJobsActEnTm() As String
            Get
                Return Me.iJobsActEnTmField
            End Get
            Set
                Me.iJobsActEnTmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IJobsActStDt() As String
            Get
                Return Me.iJobsActStDtField
            End Get
            Set
                Me.iJobsActStDtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IJobsActStTm() As String
            Get
                Return Me.iJobsActStTmField
            End Get
            Set
                Me.iJobsActStTmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ISpras() As String
            Get
                Return Me.iSprasField
            End Get
            Set
                Me.iSprasField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IUseridRf() As String
            Get
                Return Me.iUseridRfField
            End Get
            Set
                Me.iUseridRfField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IZnrWmsJobs() As Integer
            Get
                Return Me.iZnrWmsJobsField
            End Get
            Set
                Me.iZnrWmsJobsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IZwmsAppVersion() As String
            Get
                Return Me.iZwmsAppVersionField
            End Get
            Set
                Me.iZwmsAppVersionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IZwmsComputer() As String
            Get
                Return Me.iZwmsComputerField
            End Get
            Set
                Me.iZwmsComputerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IZwmsJobsStep() As String
            Get
                Return Me.iZwmsJobsStepField
            End Get
            Set
                Me.iZwmsJobsStepField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property IZwmsMatInfoTab() As ZwmsStepsExecutedMatInfo()
            Get
                Return Me.iZwmsMatInfoTabField
            End Get
            Set
                Me.iZwmsMatInfoTabField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmsStepsExecutedMatInfo
        
        Private matnrOriField As String
        
        Private werksOriField As String
        
        Private lgortOriField As String
        
        Private chargOriField As String
        
        Private qtaExecutedField As Decimal
        
        Private udmQtaExecutedField As String
        
        Private bestqField As String
        
        Private sobkzField As String
        
        Private sonumField As String
        
        Private lqnumOriField As String
        
        Private lgnumOriField As String
        
        Private lgtypOriField As String
        
        Private lgplaOriField As String
        
        Private lenumOriField As String
        
        Private letypField As String
        
        Private lqnumDestField As String
        
        Private lgnumDestField As String
        
        Private lgtypDestField As String
        
        Private lgplaDestField As String
        
        Private lenumDestField As String
        
        Private matnrDestField As String
        
        Private werksDestField As String
        
        Private lgortDestField As String
        
        Private chargDestField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MatnrOri() As String
            Get
                Return Me.matnrOriField
            End Get
            Set
                Me.matnrOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property WerksOri() As String
            Get
                Return Me.werksOriField
            End Get
            Set
                Me.werksOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgortOri() As String
            Get
                Return Me.lgortOriField
            End Get
            Set
                Me.lgortOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ChargOri() As String
            Get
                Return Me.chargOriField
            End Get
            Set
                Me.chargOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property QtaExecuted() As Decimal
            Get
                Return Me.qtaExecutedField
            End Get
            Set
                Me.qtaExecutedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UdmQtaExecuted() As String
            Get
                Return Me.udmQtaExecutedField
            End Get
            Set
                Me.udmQtaExecutedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Bestq() As String
            Get
                Return Me.bestqField
            End Get
            Set
                Me.bestqField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sobkz() As String
            Get
                Return Me.sobkzField
            End Get
            Set
                Me.sobkzField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sonum() As String
            Get
                Return Me.sonumField
            End Get
            Set
                Me.sonumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LqnumOri() As String
            Get
                Return Me.lqnumOriField
            End Get
            Set
                Me.lqnumOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgnumOri() As String
            Get
                Return Me.lgnumOriField
            End Get
            Set
                Me.lgnumOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgtypOri() As String
            Get
                Return Me.lgtypOriField
            End Get
            Set
                Me.lgtypOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgplaOri() As String
            Get
                Return Me.lgplaOriField
            End Get
            Set
                Me.lgplaOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LenumOri() As String
            Get
                Return Me.lenumOriField
            End Get
            Set
                Me.lenumOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Letyp() As String
            Get
                Return Me.letypField
            End Get
            Set
                Me.letypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LqnumDest() As String
            Get
                Return Me.lqnumDestField
            End Get
            Set
                Me.lqnumDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgnumDest() As String
            Get
                Return Me.lgnumDestField
            End Get
            Set
                Me.lgnumDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgtypDest() As String
            Get
                Return Me.lgtypDestField
            End Get
            Set
                Me.lgtypDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgplaDest() As String
            Get
                Return Me.lgplaDestField
            End Get
            Set
                Me.lgplaDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LenumDest() As String
            Get
                Return Me.lenumDestField
            End Get
            Set
                Me.lenumDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MatnrDest() As String
            Get
                Return Me.matnrDestField
            End Get
            Set
                Me.matnrDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property WerksDest() As String
            Get
                Return Me.werksDestField
            End Get
            Set
                Me.werksDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgortDest() As String
            Get
                Return Me.lgortDestField
            End Get
            Set
                Me.lgortDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ChargDest() As String
            Get
                Return Me.chargDestField
            End Get
            Set
                Me.chargDestField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmsRetStepsExecuted
        
        Private tanumField As String
        
        Private matDocNumField As String
        
        Private matDocYearField As String
        
        Private zdescrOpeExecutedField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tanum() As String
            Get
                Return Me.tanumField
            End Get
            Set
                Me.tanumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MatDocNum() As String
            Get
                Return Me.matDocNumField
            End Get
            Set
                Me.matDocNumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MatDocYear() As String
            Get
                Return Me.matDocYearField
            End Get
            Set
                Me.matDocYearField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZdescrOpeExecuted() As String
            Get
                Return Me.zdescrOpeExecutedField
            End Get
            Set
                Me.zdescrOpeExecutedField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmsJobsSteps
        
        Private mandtField As String
        
        Private znrWmsJobsField As Integer
        
        Private idJobsTypeField As String
        
        Private zwmsJobsStepField As String
        
        Private dataCreazioneField As String
        
        Private oraCreazioneField As String
        
        Private idstatusField As Short
        
        Private idJobActionField As String
        
        Private stepExecutedField As String
        
        Private singleExecutionField As String
        
        Private zwmsFinalStepField As String
        
        Private idstatusBeginField As Short
        
        Private idstatusEndField As Short
        
        Private sourcePrecOtField As String
        
        Private okForcedEndField As String
        
        Private getqtyPrevStepField As String
        
        Private lstStepForEndField As String
        
        Private frcStepDisaccField As Byte
        
        Private sequeEndStepField As Integer
        
        Private updPrintFlagField As String
        
        Private chkLastGrpJobField As String
        
        Private enableLogicOriField As String
        
        Private zpropLogicOriField As String
        
        Private zmovMmField As String
        
        Private zenaOtmovDestField As String
        
        Private zenaOtmovOriField As String
        
        Private deleField As String
        
        Private dataStartField As String
        
        Private oraStartField As String
        
        Private dataFineField As String
        
        Private oraFineField As String
        
        Private meinsOriField As String
        
        Private zqtapkOriField As Decimal
        
        Private zqtaPrelBaseField As Decimal
        
        Private udmQtaprMeinsField As String
        
        Private zqtaPrelConsField As Decimal
        
        Private udmQtaprConsField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZnrWmsJobs() As Integer
            Get
                Return Me.znrWmsJobsField
            End Get
            Set
                Me.znrWmsJobsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IdJobsType() As String
            Get
                Return Me.idJobsTypeField
            End Get
            Set
                Me.idJobsTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZwmsJobsStep() As String
            Get
                Return Me.zwmsJobsStepField
            End Get
            Set
                Me.zwmsJobsStepField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DataCreazione() As String
            Get
                Return Me.dataCreazioneField
            End Get
            Set
                Me.dataCreazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OraCreazione() As String
            Get
                Return Me.oraCreazioneField
            End Get
            Set
                Me.oraCreazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idstatus() As Short
            Get
                Return Me.idstatusField
            End Get
            Set
                Me.idstatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IdJobAction() As String
            Get
                Return Me.idJobActionField
            End Get
            Set
                Me.idJobActionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property StepExecuted() As String
            Get
                Return Me.stepExecutedField
            End Get
            Set
                Me.stepExecutedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SingleExecution() As String
            Get
                Return Me.singleExecutionField
            End Get
            Set
                Me.singleExecutionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZwmsFinalStep() As String
            Get
                Return Me.zwmsFinalStepField
            End Get
            Set
                Me.zwmsFinalStepField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IdstatusBegin() As Short
            Get
                Return Me.idstatusBeginField
            End Get
            Set
                Me.idstatusBeginField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IdstatusEnd() As Short
            Get
                Return Me.idstatusEndField
            End Get
            Set
                Me.idstatusEndField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SourcePrecOt() As String
            Get
                Return Me.sourcePrecOtField
            End Get
            Set
                Me.sourcePrecOtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OkForcedEnd() As String
            Get
                Return Me.okForcedEndField
            End Get
            Set
                Me.okForcedEndField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GetqtyPrevStep() As String
            Get
                Return Me.getqtyPrevStepField
            End Get
            Set
                Me.getqtyPrevStepField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LstStepForEnd() As String
            Get
                Return Me.lstStepForEndField
            End Get
            Set
                Me.lstStepForEndField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FrcStepDisacc() As Byte
            Get
                Return Me.frcStepDisaccField
            End Get
            Set
                Me.frcStepDisaccField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SequeEndStep() As Integer
            Get
                Return Me.sequeEndStepField
            End Get
            Set
                Me.sequeEndStepField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UpdPrintFlag() As String
            Get
                Return Me.updPrintFlagField
            End Get
            Set
                Me.updPrintFlagField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ChkLastGrpJob() As String
            Get
                Return Me.chkLastGrpJobField
            End Get
            Set
                Me.chkLastGrpJobField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EnableLogicOri() As String
            Get
                Return Me.enableLogicOriField
            End Get
            Set
                Me.enableLogicOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZpropLogicOri() As String
            Get
                Return Me.zpropLogicOriField
            End Get
            Set
                Me.zpropLogicOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZmovMm() As String
            Get
                Return Me.zmovMmField
            End Get
            Set
                Me.zmovMmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZenaOtmovDest() As String
            Get
                Return Me.zenaOtmovDestField
            End Get
            Set
                Me.zenaOtmovDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZenaOtmovOri() As String
            Get
                Return Me.zenaOtmovOriField
            End Get
            Set
                Me.zenaOtmovOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Dele() As String
            Get
                Return Me.deleField
            End Get
            Set
                Me.deleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DataStart() As String
            Get
                Return Me.dataStartField
            End Get
            Set
                Me.dataStartField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OraStart() As String
            Get
                Return Me.oraStartField
            End Get
            Set
                Me.oraStartField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DataFine() As String
            Get
                Return Me.dataFineField
            End Get
            Set
                Me.dataFineField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OraFine() As String
            Get
                Return Me.oraFineField
            End Get
            Set
                Me.oraFineField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MeinsOri() As String
            Get
                Return Me.meinsOriField
            End Get
            Set
                Me.meinsOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZqtapkOri() As Decimal
            Get
                Return Me.zqtapkOriField
            End Get
            Set
                Me.zqtapkOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZqtaPrelBase() As Decimal
            Get
                Return Me.zqtaPrelBaseField
            End Get
            Set
                Me.zqtaPrelBaseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UdmQtaprMeins() As String
            Get
                Return Me.udmQtaprMeinsField
            End Get
            Set
                Me.udmQtaprMeinsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZqtaPrelCons() As Decimal
            Get
                Return Me.zqtaPrelConsField
            End Get
            Set
                Me.zqtaPrelConsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UdmQtaprCons() As String
            Get
                Return Me.udmQtaprConsField
            End Get
            Set
                Me.udmQtaprConsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmsJobs
        
        Private mandtField As String
        
        Private znrWmsJobsField As Integer
        
        Private sequenceField As Integer
        
        Private sequencePrintField As Integer
        
        Private execPrintField As String
        
        Private printDoneField As String
        
        Private currentStepField As Byte
        
        Private numStepsTotalField As String
        
        Private dataCreazioneField As String
        
        Private oraCreazioneField As String
        
        Private pickDbtabnameField As String
        
        Private znrpickField As String
        
        Private zpospkField As String
        
        Private vbelnField As String
        
        Private posnrField As String
        
        Private numConsVbelvField As String
        
        Private posConsPosnvField As String
        
        Private kunnrAgField As String
        
        Private kunnrWeField As String
        
        Private kunnrRgField As String
        
        Private znrWmsJobsgrpField As String
        
        Private znrWmsGrpexecField As Integer
        
        Private mblnrField As String
        
        Private mjahrField As String
        
        Private zeileField As String
        
        Private idstatusField As Short
        
        Private idJobsTypeField As String
        
        Private idWmsDevicesField As String
        
        Private prioritaField As Integer
        
        Private urgenteField As String
        
        Private matnrOriField As String
        
        Private werksOriField As String
        
        Private lgortOriField As String
        
        Private chargOriField As String
        
        Private bestqOriField As String
        
        Private sobkzOriField As String
        
        Private sonumOriField As String
        
        Private meinsOriField As String
        
        Private zqtapkOriField As Decimal
        
        Private meinsPzField As String
        
        Private zqtapkOriPzField As Decimal
        
        Private zqtaPrelBaseField As Decimal
        
        Private udmQtaprMeinsField As String
        
        Private zqtaPrelConsField As Decimal
        
        Private udmQtaprConsField As String
        
        Private zqtaPrelPzField As Decimal
        
        Private udmQtaprPzField As String
        
        Private zflawmField As String
        
        Private palletInteriField As String
        
        Private scatoleIntereField As String
        
        Private ztipoEntmerceField As String
        
        Private zforceddestField As String
        
        Private zforcspuntaconfField As String
        
        Private zcarrPropField As String
        
        Private zcarrExecField As String
        
        Private lgnumOriField As String
        
        Private lgtypOriField As String
        
        Private lgplaOriField As String
        
        Private lenumOriField As String
        
        Private lgnumDestField As String
        
        Private lgtypDestField As String
        
        Private lgplaDestField As String
        
        Private lenumDestField As String
        
        Private matnrDestField As String
        
        Private werksDestField As String
        
        Private lgortDestField As String
        
        Private chargDestField As String
        
        Private bestqDestField As String
        
        Private sobkzDestField As String
        
        Private sonumDestField As String
        
        Private lgnumPropOriField As String
        
        Private lgtypPropOriField As String
        
        Private lgplaPropOriField As String
        
        Private lenumPropOriField As String
        
        Private okQtaPropOriField As String
        
        Private lgnumPropDestField As String
        
        Private lgtypPropDestField As String
        
        Private lgplaPropDestField As String
        
        Private lenumPropDestField As String
        
        Private okQtaPropDestField As String
        
        Private chargTassativaField As String
        
        Private zdocField As String
        
        Private fornitoreLifnrField As String
        
        Private deleField As String
        
        Private memoField As String
        
        Private zzNdisField As String
        
        Private ernamField As String
        
        Private erdatField As String
        
        Private erzeitField As String
        
        Private aenamField As String
        
        Private aedatField As String
        
        Private aezeitField As String
        
        Private dataStartField As String
        
        Private oraStartField As String
        
        Private dataFineField As String
        
        Private oraFineField As String
        
        Private znrWmsJobsOriField As Integer
        
        Private zwmsjobsgrpOriField As String
        
        Private infoPrelievoField As String
        
        Private znrWmsJobsCarField As String
        
        Private ltkzeField As String
        
        Private ltkzaField As String
        
        Private zmatnrChkPronField As String
        
        Private zjobsShippedField As String
        
        Private zjobsShipConsField As String
        
        Private zjobsShipConpField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZnrWmsJobs() As Integer
            Get
                Return Me.znrWmsJobsField
            End Get
            Set
                Me.znrWmsJobsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sequence() As Integer
            Get
                Return Me.sequenceField
            End Get
            Set
                Me.sequenceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SequencePrint() As Integer
            Get
                Return Me.sequencePrintField
            End Get
            Set
                Me.sequencePrintField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ExecPrint() As String
            Get
                Return Me.execPrintField
            End Get
            Set
                Me.execPrintField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PrintDone() As String
            Get
                Return Me.printDoneField
            End Get
            Set
                Me.printDoneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CurrentStep() As Byte
            Get
                Return Me.currentStepField
            End Get
            Set
                Me.currentStepField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NumStepsTotal() As String
            Get
                Return Me.numStepsTotalField
            End Get
            Set
                Me.numStepsTotalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DataCreazione() As String
            Get
                Return Me.dataCreazioneField
            End Get
            Set
                Me.dataCreazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OraCreazione() As String
            Get
                Return Me.oraCreazioneField
            End Get
            Set
                Me.oraCreazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PickDbtabname() As String
            Get
                Return Me.pickDbtabnameField
            End Get
            Set
                Me.pickDbtabnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Znrpick() As String
            Get
                Return Me.znrpickField
            End Get
            Set
                Me.znrpickField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zpospk() As String
            Get
                Return Me.zpospkField
            End Get
            Set
                Me.zpospkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vbeln() As String
            Get
                Return Me.vbelnField
            End Get
            Set
                Me.vbelnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Posnr() As String
            Get
                Return Me.posnrField
            End Get
            Set
                Me.posnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NumConsVbelv() As String
            Get
                Return Me.numConsVbelvField
            End Get
            Set
                Me.numConsVbelvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PosConsPosnv() As String
            Get
                Return Me.posConsPosnvField
            End Get
            Set
                Me.posConsPosnvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property KunnrAg() As String
            Get
                Return Me.kunnrAgField
            End Get
            Set
                Me.kunnrAgField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property KunnrWe() As String
            Get
                Return Me.kunnrWeField
            End Get
            Set
                Me.kunnrWeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property KunnrRg() As String
            Get
                Return Me.kunnrRgField
            End Get
            Set
                Me.kunnrRgField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZnrWmsJobsgrp() As String
            Get
                Return Me.znrWmsJobsgrpField
            End Get
            Set
                Me.znrWmsJobsgrpField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZnrWmsGrpexec() As Integer
            Get
                Return Me.znrWmsGrpexecField
            End Get
            Set
                Me.znrWmsGrpexecField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mblnr() As String
            Get
                Return Me.mblnrField
            End Get
            Set
                Me.mblnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mjahr() As String
            Get
                Return Me.mjahrField
            End Get
            Set
                Me.mjahrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zeile() As String
            Get
                Return Me.zeileField
            End Get
            Set
                Me.zeileField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Idstatus() As Short
            Get
                Return Me.idstatusField
            End Get
            Set
                Me.idstatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IdJobsType() As String
            Get
                Return Me.idJobsTypeField
            End Get
            Set
                Me.idJobsTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IdWmsDevices() As String
            Get
                Return Me.idWmsDevicesField
            End Get
            Set
                Me.idWmsDevicesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Priorita() As Integer
            Get
                Return Me.prioritaField
            End Get
            Set
                Me.prioritaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Urgente() As String
            Get
                Return Me.urgenteField
            End Get
            Set
                Me.urgenteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MatnrOri() As String
            Get
                Return Me.matnrOriField
            End Get
            Set
                Me.matnrOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property WerksOri() As String
            Get
                Return Me.werksOriField
            End Get
            Set
                Me.werksOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgortOri() As String
            Get
                Return Me.lgortOriField
            End Get
            Set
                Me.lgortOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ChargOri() As String
            Get
                Return Me.chargOriField
            End Get
            Set
                Me.chargOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BestqOri() As String
            Get
                Return Me.bestqOriField
            End Get
            Set
                Me.bestqOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SobkzOri() As String
            Get
                Return Me.sobkzOriField
            End Get
            Set
                Me.sobkzOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SonumOri() As String
            Get
                Return Me.sonumOriField
            End Get
            Set
                Me.sonumOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MeinsOri() As String
            Get
                Return Me.meinsOriField
            End Get
            Set
                Me.meinsOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZqtapkOri() As Decimal
            Get
                Return Me.zqtapkOriField
            End Get
            Set
                Me.zqtapkOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MeinsPz() As String
            Get
                Return Me.meinsPzField
            End Get
            Set
                Me.meinsPzField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZqtapkOriPz() As Decimal
            Get
                Return Me.zqtapkOriPzField
            End Get
            Set
                Me.zqtapkOriPzField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZqtaPrelBase() As Decimal
            Get
                Return Me.zqtaPrelBaseField
            End Get
            Set
                Me.zqtaPrelBaseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UdmQtaprMeins() As String
            Get
                Return Me.udmQtaprMeinsField
            End Get
            Set
                Me.udmQtaprMeinsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZqtaPrelCons() As Decimal
            Get
                Return Me.zqtaPrelConsField
            End Get
            Set
                Me.zqtaPrelConsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UdmQtaprCons() As String
            Get
                Return Me.udmQtaprConsField
            End Get
            Set
                Me.udmQtaprConsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZqtaPrelPz() As Decimal
            Get
                Return Me.zqtaPrelPzField
            End Get
            Set
                Me.zqtaPrelPzField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UdmQtaprPz() As String
            Get
                Return Me.udmQtaprPzField
            End Get
            Set
                Me.udmQtaprPzField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zflawm() As String
            Get
                Return Me.zflawmField
            End Get
            Set
                Me.zflawmField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PalletInteri() As String
            Get
                Return Me.palletInteriField
            End Get
            Set
                Me.palletInteriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ScatoleIntere() As String
            Get
                Return Me.scatoleIntereField
            End Get
            Set
                Me.scatoleIntereField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZtipoEntmerce() As String
            Get
                Return Me.ztipoEntmerceField
            End Get
            Set
                Me.ztipoEntmerceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zforceddest() As String
            Get
                Return Me.zforceddestField
            End Get
            Set
                Me.zforceddestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zforcspuntaconf() As String
            Get
                Return Me.zforcspuntaconfField
            End Get
            Set
                Me.zforcspuntaconfField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZcarrProp() As String
            Get
                Return Me.zcarrPropField
            End Get
            Set
                Me.zcarrPropField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZcarrExec() As String
            Get
                Return Me.zcarrExecField
            End Get
            Set
                Me.zcarrExecField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgnumOri() As String
            Get
                Return Me.lgnumOriField
            End Get
            Set
                Me.lgnumOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgtypOri() As String
            Get
                Return Me.lgtypOriField
            End Get
            Set
                Me.lgtypOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgplaOri() As String
            Get
                Return Me.lgplaOriField
            End Get
            Set
                Me.lgplaOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LenumOri() As String
            Get
                Return Me.lenumOriField
            End Get
            Set
                Me.lenumOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgnumDest() As String
            Get
                Return Me.lgnumDestField
            End Get
            Set
                Me.lgnumDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgtypDest() As String
            Get
                Return Me.lgtypDestField
            End Get
            Set
                Me.lgtypDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgplaDest() As String
            Get
                Return Me.lgplaDestField
            End Get
            Set
                Me.lgplaDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LenumDest() As String
            Get
                Return Me.lenumDestField
            End Get
            Set
                Me.lenumDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MatnrDest() As String
            Get
                Return Me.matnrDestField
            End Get
            Set
                Me.matnrDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property WerksDest() As String
            Get
                Return Me.werksDestField
            End Get
            Set
                Me.werksDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgortDest() As String
            Get
                Return Me.lgortDestField
            End Get
            Set
                Me.lgortDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ChargDest() As String
            Get
                Return Me.chargDestField
            End Get
            Set
                Me.chargDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BestqDest() As String
            Get
                Return Me.bestqDestField
            End Get
            Set
                Me.bestqDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SobkzDest() As String
            Get
                Return Me.sobkzDestField
            End Get
            Set
                Me.sobkzDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SonumDest() As String
            Get
                Return Me.sonumDestField
            End Get
            Set
                Me.sonumDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgnumPropOri() As String
            Get
                Return Me.lgnumPropOriField
            End Get
            Set
                Me.lgnumPropOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgtypPropOri() As String
            Get
                Return Me.lgtypPropOriField
            End Get
            Set
                Me.lgtypPropOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgplaPropOri() As String
            Get
                Return Me.lgplaPropOriField
            End Get
            Set
                Me.lgplaPropOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LenumPropOri() As String
            Get
                Return Me.lenumPropOriField
            End Get
            Set
                Me.lenumPropOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OkQtaPropOri() As String
            Get
                Return Me.okQtaPropOriField
            End Get
            Set
                Me.okQtaPropOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgnumPropDest() As String
            Get
                Return Me.lgnumPropDestField
            End Get
            Set
                Me.lgnumPropDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgtypPropDest() As String
            Get
                Return Me.lgtypPropDestField
            End Get
            Set
                Me.lgtypPropDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LgplaPropDest() As String
            Get
                Return Me.lgplaPropDestField
            End Get
            Set
                Me.lgplaPropDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LenumPropDest() As String
            Get
                Return Me.lenumPropDestField
            End Get
            Set
                Me.lenumPropDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OkQtaPropDest() As String
            Get
                Return Me.okQtaPropDestField
            End Get
            Set
                Me.okQtaPropDestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ChargTassativa() As String
            Get
                Return Me.chargTassativaField
            End Get
            Set
                Me.chargTassativaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Zdoc() As String
            Get
                Return Me.zdocField
            End Get
            Set
                Me.zdocField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FornitoreLifnr() As String
            Get
                Return Me.fornitoreLifnrField
            End Get
            Set
                Me.fornitoreLifnrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Dele() As String
            Get
                Return Me.deleField
            End Get
            Set
                Me.deleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Memo() As String
            Get
                Return Me.memoField
            End Get
            Set
                Me.memoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZzNdis() As String
            Get
                Return Me.zzNdisField
            End Get
            Set
                Me.zzNdisField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ernam() As String
            Get
                Return Me.ernamField
            End Get
            Set
                Me.ernamField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Erdat() As String
            Get
                Return Me.erdatField
            End Get
            Set
                Me.erdatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Erzeit() As String
            Get
                Return Me.erzeitField
            End Get
            Set
                Me.erzeitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Aenam() As String
            Get
                Return Me.aenamField
            End Get
            Set
                Me.aenamField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Aedat() As String
            Get
                Return Me.aedatField
            End Get
            Set
                Me.aedatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Aezeit() As String
            Get
                Return Me.aezeitField
            End Get
            Set
                Me.aezeitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DataStart() As String
            Get
                Return Me.dataStartField
            End Get
            Set
                Me.dataStartField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OraStart() As String
            Get
                Return Me.oraStartField
            End Get
            Set
                Me.oraStartField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DataFine() As String
            Get
                Return Me.dataFineField
            End Get
            Set
                Me.dataFineField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OraFine() As String
            Get
                Return Me.oraFineField
            End Get
            Set
                Me.oraFineField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZnrWmsJobsOri() As Integer
            Get
                Return Me.znrWmsJobsOriField
            End Get
            Set
                Me.znrWmsJobsOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZwmsjobsgrpOri() As String
            Get
                Return Me.zwmsjobsgrpOriField
            End Get
            Set
                Me.zwmsjobsgrpOriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property InfoPrelievo() As String
            Get
                Return Me.infoPrelievoField
            End Get
            Set
                Me.infoPrelievoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZnrWmsJobsCar() As String
            Get
                Return Me.znrWmsJobsCarField
            End Get
            Set
                Me.znrWmsJobsCarField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ltkze() As String
            Get
                Return Me.ltkzeField
            End Get
            Set
                Me.ltkzeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ltkza() As String
            Get
                Return Me.ltkzaField
            End Get
            Set
                Me.ltkzaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZmatnrChkPron() As String
            Get
                Return Me.zmatnrChkPronField
            End Get
            Set
                Me.zmatnrChkPronField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZjobsShipped() As String
            Get
                Return Me.zjobsShippedField
            End Get
            Set
                Me.zjobsShippedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZjobsShipCons() As String
            Get
                Return Me.zjobsShipConsField
            End Get
            Set
                Me.zjobsShipConsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZjobsShipConp() As String
            Get
                Return Me.zjobsShipConpField
            End Get
            Set
                Me.zjobsShipConpField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class Bapiret2
        
        Private typeField As String
        
        Private idField As String
        
        Private numberField As String
        
        Private messageField As String
        
        Private logNoField As String
        
        Private logMsgNoField As String
        
        Private messageV1Field As String
        
        Private messageV2Field As String
        
        Private messageV3Field As String
        
        Private messageV4Field As String
        
        Private parameterField As String
        
        Private rowField As Integer
        
        Private fieldField As String
        
        Private systemField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set(value As String)
                Me.typeField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Number() As String
            Get
                Return Me.numberField
            End Get
            Set(value As String)
                Me.numberField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set(value As String)
                Me.messageField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property LogNo() As String
            Get
                Return Me.logNoField
            End Get
            Set(value As String)
                Me.logNoField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property LogMsgNo() As String
            Get
                Return Me.logMsgNoField
            End Get
            Set(value As String)
                Me.logMsgNoField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV1() As String
            Get
                Return Me.messageV1Field
            End Get
            Set(value As String)
                Me.messageV1Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV2() As String
            Get
                Return Me.messageV2Field
            End Get
            Set(value As String)
                Me.messageV2Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV3() As String
            Get
                Return Me.messageV3Field
            End Get
            Set(value As String)
                Me.messageV3Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property MessageV4() As String
            Get
                Return Me.messageV4Field
            End Get
            Set(value As String)
                Me.messageV4Field = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Parameter() As String
            Get
                Return Me.parameterField
            End Get
            Set(value As String)
                Me.parameterField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Row() As Integer
            Get
                Return Me.rowField
            End Get
            Set(value As Integer)
                Me.rowField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property Field() As String
            Get
                Return Me.fieldField
            End Get
            Set(value As String)
                Me.fieldField = Value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=Xml.Schema.XmlSchemaForm.Unqualified)> _
        Public Property System() As String
            Get
                Return Me.systemField
            End Get
            Set(value As String)
                Me.systemField = Value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZwmsJobEmStepsExecutedResponse
        
        Private eErrorCodeField As String
        
        Private eErrorDescriptionField As String
        
        Private eErrorSubrcField As Integer
        
        Private eReturnField As Bapiret2
        
        Private eSuccessField As String
        
        Private eWritedrowsField As Integer
        
        Private eZwmsJobsRecField As ZwmsJobs
        
        Private eZwmsJobsStepsRecField As ZwmsJobsSteps
        
        Private eZwmsRetStepsExecutedTabField() As ZwmsRetStepsExecuted
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorCode() As String
            Get
                Return Me.eErrorCodeField
            End Get
            Set
                Me.eErrorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorDescription() As String
            Get
                Return Me.eErrorDescriptionField
            End Get
            Set
                Me.eErrorDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EErrorSubrc() As Integer
            Get
                Return Me.eErrorSubrcField
            End Get
            Set
                Me.eErrorSubrcField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EReturn() As Bapiret2
            Get
                Return Me.eReturnField
            End Get
            Set
                Me.eReturnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ESuccess() As String
            Get
                Return Me.eSuccessField
            End Get
            Set
                Me.eSuccessField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EWritedrows() As Integer
            Get
                Return Me.eWritedrowsField
            End Get
            Set
                Me.eWritedrowsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EZwmsJobsRec() As ZwmsJobs
            Get
                Return Me.eZwmsJobsRecField
            End Get
            Set
                Me.eZwmsJobsRecField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EZwmsJobsStepsRec() As ZwmsJobsSteps
            Get
                Return Me.eZwmsJobsStepsRecField
            End Get
            Set
                Me.eZwmsJobsStepsRecField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property EZwmsRetStepsExecutedTab() As ZwmsRetStepsExecuted()
            Get
                Return Me.eZwmsRetStepsExecutedTabField
            End Get
            Set
                Me.eZwmsRetStepsExecutedTabField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ZwmsJobEmStepsExecutedCompletedEventHandler(ByVal sender As Object, ByVal e As ZwmsJobEmStepsExecutedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZwmsJobEmStepsExecutedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZwmsJobEmStepsExecutedResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZwmsJobEmStepsExecutedResponse)
            End Get
        End Property
    End Class
End Namespace
